### ISSUE TITLE
Cannot find treemacs-tab-bar

### ISSUE THREAD

**Issue by darim1** [Alexander-Miller/treemacs#911] opened 2022-02-26 15:10 UTC
I encounter some troubles, trying to find out how treemacs and built-in tab-bar complement. Following the excellent guide, there should be some additional package treemacs-tab-bar. This is, however, not findable.

I could assume two reasons: First, the support has moved into the main treemacs package. Second, the guide is somehow ahead. 

Can someone please provide me further information?

One additional remark: It appears that treemacs and tab-bar don't integrate seemlessly without the additional package. Whenever I switch the workspace in the first tab, treemacs would close in the second tab. My hope is, that treemacs-tab-bar will fix this.

**Comment by Alexander-Miller** [comment] 2022-04-28 11:25
The package is [right here on melpa](https://melpa.org/#/treemacs-tab-bar). Judging by the age of this issue it's possible you couldn't find it because it hadn't been published yet - it can take a while until melpa's PRs are merged - but it's definitely available now.

> It appears that treemacs and tab-bar don't integrate seemlessly

I don't use tabs myself, so I will need a step-by-step reproduction to understand what's going on here.

**Comment by darim1** [comment] 2022-05-09 11:32
I'll check it, thanks. Tab-bar stuff was reported here: https://github.com/Alexander-Miller/treemacs/issues/920

Thanks!

**Closed** 2022-05-09 18:53 UTC
Labels: Question/Discussion, Feature: Tab Bar
