### ISSUE TITLE
Add project: Error running timer 'pulse-tick'

### ISSUE THREAD

**Issue by is-r-not-j** [Alexander-Miller/treemacs#249] opened 2018-08-01 11:03 UTC
When I try to add a project using C-p a, I get:

`Error running timer 'pulse-tick': (args-out-of-range -1 -1)`

**Comment by Alexander-Miller** [comment] 2018-08-01 11:08
* Under what conditions?
 * What's the rest of your workspace look like?
 * Is the project added anyway?
 * Set `enable-debu-on-error` to t and then show me a stack trace.
 * Is your treemacs install up-to-date?

**Comment by Alexander-Miller** [comment] 2018-08-13 11:37
The base error is the same, but they're thrown in completely separate parts of the code, though I guess there's a chance both are caused by the same underlying problem.

Is this issue reproducible somehow, does it happen consistently?

**Comment by myrgy** [comment] 2018-08-14 07:01
I use spacemacs with treemacs, 
STR:
 open some project, then switch file using `SPS p f`, switch to not opened file.
Error will appear.

**Comment by Alexander-Miller** [comment] 2018-08-14 08:51
Do you use emacs as a systemd service, or a server with emacsclient or something similar?

**Comment by Alexander-Miller** [comment] 2018-08-14 16:38
Ah, I've found the issue. Long story short I should've used with-selected-window instead of with-current-buffer. Patch will come soon, at least the follow error will be solved then.

**Comment by myrgy** [comment] 2018-08-17 08:14
@Alexander-Miller , I don't observe issue any more. Thanks a lot!

**Comment by is-r-not-j** [comment] 2018-08-20 11:31
Hi, the issue remains for me. There's nothing special about my config that I could think of, pretty vanilla emacs with just a few packages.

I did disable png images though, might be related!

Stack trace is:

Debugger entered--Lisp error: (args-out-of-range -1 -1)
  get-text-property(-1 display)
  treemacs--pulse-png-advice()
  apply(treemacs--pulse-png-advice nil)
  pulse-lighten-highlight()
  pulse-tick((23418 42407 775818 999999))
  apply(pulse-tick (23418 42407 775818 999999))
  timer-event-handler([t 23418 42407 505823 0.03 pulse-tick ((23418 42407 775818 999999)) nil 999999])

**Comment by Alexander-Miller** [comment] 2018-08-20 15:03
> yep, enabling png images did allow me to add a project!

Good. If I know it I can fix it.

>  would be nice to be able to add projects through cusotmisation variables to have them in init file

That is not the current course, though a better interface is on the way as part of the larger workspace initiative. You can basically achieve something similar by customizing `treemacs-persist-file`. I've recently switched the persist format to be a small subset of org-mode. So you can just point the persist file to an org file next to your init. 

I also plan to introduce a command that will pop up and org mode buffer with the current workspace state to allow quick edits.

I will however take a small break here because I want to kick off https://github.com/Alexander-Miller/treemacs/issues/263 with @yyoncho.

**Comment by Alexander-Miller** [comment] 2018-08-20 17:13
@is-r-not-j I've just pushed a couple of patches, your issues should be fixed now.

**Comment by Alexander-Miller** [comment] 2018-08-30 05:07
I assume all is done here.

**Closed by Alexander-Miller** 2018-08-30 05:07 UTC
Labels: Bug
