### ISSUE TITLE
xterm-mouse-mode menus fail

### ISSUE THREAD

**Issue by perkinslr** [Alexander-Miller/treemacs#690] opened 2020-06-30 07:13 UTC
When running in a terminal, with `xterm-mouse-mode` enabled (and probably `gpm-mouse-mode`), right clicking on a treemacs menu item brings up a (nicely formatted) menu.  If I then use the keyboard to select the "copy" item, I get a usable (albeit unpolished) interface to specify a destination.  If, however, I click the button with the mouse, I get the following error (displayed in the message buffer).

`Wrong type argument: commandp, (keymap "New" (New\ File menu-item "New File" treemacs-create-file) (New\ Directory menu-item "New Directory" treemacs-create-dir))`

It is likely a quick fix (to at least make it functional) as if the frame is a text mode frame, it just needs to follow the same code path as the keyboard.

**Comment by Alexander-Miller** [comment] 2020-06-30 22:04
Looking into it.

**Comment by Alexander-Miller** [comment] 2020-07-01 12:21
Have to close this because by the looks of things Emacs does not support mouse menu selection in the terminal. `xterm-mouse-mode` will only enable basic mouse interactions, its documentation says:

> It only works for simple uses of the mouse.  Basically, only non-modified single clicks are supported.

So there's nothing I can do about this on my end.

Here's some reproduction code I used:

```Elisp
(defun testclick (event)
  (interactive "e")
  (let* ((menu
          (easy-menu-create-menu
           nil
           `(["A" ignore]
             ["B" ignore]
             ["C" ignore])))
         (choice (x-popup-menu event menu)))
    (message "Selected Option %s" choice)))

(define-key (current-local-map) [mouse-1] #'testclick)
```

You can see that the mouse click does trigger the menu, but does not set selection, so you just end up with whatever menu item is selected with the keyboard.

BTW

> I get a usable (albeit unpolished) interface to specify a destination.

What's supposed to be unpolished about this? I am using the builtin `read-file-name` command here.

**Closed by Alexander-Miller** 2020-07-01 12:21 UTC
Labels: Bug, Feature:Mouse Interface

**Comment by perkinslr** [comment] 2020-07-02 07:14
So, `xterm-mouse-mode` does report the location of the mouse click event.  You can see that this is the case as the location of the popup menu is relative to the click.  The problem is the popup created by `x-popup-menu` doesn't properly handle the click event to update its selection before firing.  If you click and drag, it will deselect all options, and then report "nil" as the selected option.  Regardless, assuming treemacs is just using `x-popup-menu` under the hood, the problem doesn't lie with treemacs, and I don't see a trivial workaround for it.  If time allows, I may see if I can fix it and open a discussion on the mailing list about getting it fixed upstream.

I probably should have said simple or basic, rather than unpolished.  When running in gtk mode, selecting copy from the menu with the mouse pops up a file chooser, letting you use the mouse to go pick the destination file.  If I'm using a tree file explorer, it's generally because I want to avoid typing paths (mostly when working with datasets with multiple nested uuid-based directory names).  It would be super neat (and the only side-panel directory/project browser for emacs) if treemacs had some way to use treemacs itself to pick the destination, rather than falling back to a typed path.

**Comment by Alexander-Miller** [comment] 2020-07-03 10:04
> assuming treemacs is just using x-popup-menu under the hood,

It does. The example code above is a small version of what treemacs is doing.

> When running in gtk mode, selecting copy from the menu with the mouse pops up a file chooser

Ah, I didn't know Emacs does that. I just see the same helm prompt in both GUI and TUI. I've looked around and found you can manually call that graphical file chooser with `x-file-dialog`, but that fails in terminal frames. I'll open an issue for making that dialog the preferred choice, but the terminal selection will have to stay as is.

> It would be super neat (and the only side-panel directory/project browser for emacs) if treemacs had some way to use treemacs itself to pick the destination

That would look pretty weird without popping up a new child frame, so I'd rather wait for Emacs27 to be released.
