### ISSUE TITLE
File position on file tree is wrong when creating new file

### ISSUE THREAD

**Issue by Isoltsame** [Alexander-Miller/treemacs#560] opened 2019-11-06 21:25 UTC
When I create a file named "file3" inside "Folder2" treemacs auto refresh (after I save the new file) puts it below 'AnotherFile1' like this:

Folder1
   | - Folder2
   |     | - file1
   |     | - file2
   | - AnotherFile1
   |     | - file3
   | - AnotherFile2

instead of:

Folder1
   | - Folder2
   |     | - file1
   |     | - file2
   |     | - file3
   | - AnotherFile1
   | - AnotherFile2

![bug](https://user-images.githubusercontent.com/10102483/68338578-8f3c4000-00c1-11ea-9ab8-234cdfae8f04.png)

**Comment by Alexander-Miller** [comment] 2019-11-07 05:55
[Works on my end](https://imgur.com/a/ijuOX3m)

What version are you on? I pushed a large pile of updates just yesterday, and update behavior was right at the heart of that pile, so make sure your treemacs is up-to-date.

**Comment by KenjiGashu** [comment] 2019-11-08 13:21
It's working after I updated

**Comment by Isoltsame** [comment] 2019-11-13 19:05
Sorry, i answered with wrong account.
I tested it again and it's working after I updated

**Comment by thomassross** [comment] 2019-11-30 21:42
I'm running into this issue occasionally, without creating new files or any interaction with treemacs (i.e. it happens when treemacs automatically refreshes and I'm doing other stuff, like committing in magit)

I have `treemacs-git-mode` completely off (` = nil`), but `treemacs-collapse-dirs` is at its default setting for me (`3`), so maybe #558 is related?

Here are my settings, excluding keybinds:
```lisp
(setq treemacs-width 30)
(setq treemacs-silent-refresh t)
(setq treemacs-is-never-other-window t)
(setq treemacs-python-executable "/usr/bin/python3")
(setq treemacs-git-mode nil)
(setq treemacs-eldoc-display nil)

(treemacs-resize-icons 15)
(treemacs-fringe-indicator-mode 0)
(treemacs-follow-mode -1)

(with-eval-after-load 'treemacs
  (defun treemacs-ignore-pyc (file _)
    (string-suffix-p ".pyc" file))
  (push 'treemacs-ignore-pyc treemacs-ignored-file-predicates))
```

**Comment by Alexander-Miller** [comment] 2019-12-02 05:58
If you are not creating new files, then what do your problems look like exactly? Ideally I would need an example screenshot.

And as usual make sure your treemacs is up to date. I have touched up the file-insert parts only a couple commit ago.

**Comment by thomassross** [comment] 2019-12-02 06:05
I'm not at my computer at the moment and the issue is hard to reproduce but the file was displayed in the wrong folder (in the next folder down the list, similar to the screenshot @lsoltsame posted.) 

Sometimes files also disappear from the list while still on disk. It seems to usually be the file I'm editing but that could be a coincidence.

My treemacs is up to date (latest from melpa)

**Comment by Alexander-Miller** [comment] 2019-12-02 09:17
> I'm not at my computer at the moment and the issue is hard to reproduce but the file was displayed in the wrong folder

But it should be deterministic, so if you see it happen once you should be able to make it happen again. The type of item created (file or dir), the directory inserted into and the names of the files and dirs already in it are all important since there's some fairly complex matching happening to find the right insert spot.

> Sometimes files also disappear from the list while still on disk. It seems to usually be the file I'm editing but that could be a coincidence.

Treemacs remembers a modified file's last git state, so to test this you would have to make edits that change a file state to changed <-> clean.

**Comment by thomassross** [comment] 2019-12-04 23:12
> But it should be deterministic, so if you see it happen once you should be able to make it happen again. The type of item created (file or dir), the directory inserted into and the names of the files and dirs already in it are all important since there's some fairly complex matching happening to find the right insert spot.

I will update this thread when I see it happen again and I'll try to make steps to reproduce it. I will have to keep a closer eye on my treemacs window since I usually don't notice it until a few commands after it's happened.

**Comment by thomassross** [comment] 2020-02-13 05:08
I haven't been able to reproduce this bug recently (in the past few weeks).

I did run into this a few minutes ago though, no idea what caused it. Treemacs was completely unresponsive (`treemacs-select-window` didn't work) till I toggled (`treemacs`) it twice. Not sure if it's related - would you like me to open a new issue for it?

![Screenshot_2020-02-13_00-03-44](https://user-images.githubusercontent.com/3471434/74403263-a3948500-4df4-11ea-82d3-fc4dd708ae85.png)

Note the double folder icon in the top left, as well as the red and blue projects on the same line (I can't expand or close either of them. I can however use the file tree below it as if it was the file tree for the red project. Actually, the blue project is the same as the first project (the one on line 1). I can use the project on line 1 as expected. The double folder icon reduces to a single folder icon when my cursor is on it, but goes back to a double folder icon when I move my cursor away (even when the project is expanded).

**Comment by Alexander-Miller** [comment] 2020-02-15 13:18
> Treemacs was completely unresponsive (treemacs-select-window didn't work)

Are you on spacemacs or using the new persp-mode scope feature (check what `(treemacs-current-scope-type)` returns)? That stuff is likely to be buggy in some corners and an update is on the way.

> Note the double folder icon in the top left, as well as the red and blue projects on the same line

Reminds me of some of the bugs I ran into mid-development, but that was long ago now. You should open an issue if you have a recipe to reproduce it, otherwise there's won't be anything I can do about it.

**Comment by thomassross** [comment] 2020-02-18 19:35
No, I'm not on Spacemacs. `treemacs-current-scope-type` returns value `'treemacs-frame-scope`.

I think we should just close this issue. Reproducing these bugs is pretty difficult, If I manage to, I'll open a new issue.

Thanks!

**Comment by Alexander-Miller** [comment] 2020-02-19 06:32
:+1:

**Closed by Alexander-Miller** 2020-02-19 06:32 UTC
