### ISSUE TITLE
treemacs-do-update-single-file-git-state: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by Nekosis** [Alexander-Miller/treemacs#1064] opened 2023-09-29 00:35 UTC
Writing a file with Treemacs open results in an error in `*Messages*`:

`treemacs-do-update-single-file-git-state: Wrong type argument: hash-table-p, nil`

Weirdly, the document I am editing is **not** in a Git repository. It is an Org document, if that helps.

**Comment by Nekosis** [comment] 2023-09-29 01:56
Nevermind, fixed itself...

**Comment by Alexander-Miller** [comment] 2023-09-29 11:06
It probably happened because the treemacs buffer was in an inconsistent state due to some previous hiccup, so restarting it would fix the problem.

If it happens again you should enable debug-on-error and provide the stack trace.

**Comment by Nekosis** [comment] 2023-09-30 06:20
It indeed happened again :/ and restarting Emacs doesn't seem to fix it.

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/home/[NAME REDACTED]" nil nil)
  treemacs-do-update-single-file-git-state("/home/[NAME REDACTED]/Downloads")
  treemacs-update-single-file-git-state("/home/[NAME REDACTED]/Downloads")
  treemacs--filewatch-callback(((8 . 0) deleted "/home/[NAME REDACTED]/Downloads/thingy.py"))
  file-notify--handle-event((8 . 0) (changed) "thingy.py" 0)
  file-notify--callback-inotify(((8 . 0) (modify) "thingy.py" 0))
  file-notify-handle-event((file-notify ((8 . 0) (modify) "thingy.py" 0) file-notify--callback-inotify))
  funcall-interactively(file-notify-handle-event (file-notify ((8 . 0) (modify) "thingy.py" 0) file-notify--callback-inotify))
  call-interactively(file-notify-handle-event nil [(file-notify ((8 . 0) (modify) "thingy.py" 0) file-notify--callback-inotify)])
  command-execute(file-notify-handle-event nil [(file-notify ((8 . 0) (modify) "thingy.py" 0) file-notify--callback-inotify)] t)
```

**Comment by anticrisis** [comment] 2023-09-30 08:56
This started happening to me too, after updating treemacs sometime in the past week. Also, none of my directories are git repositories.

**Comment by anticrisis** [comment] 2023-09-30 09:01
In my case, I think it's because a journal file is being created and deleted rapidly by another emacs package:

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  treemacs-do-update-single-file-git-state("/home/anticrisis/dev/lisp/ml")
  treemacs-update-single-file-git-state("/home/anticrisis/dev/lisp/ml")
  treemacs--filewatch-callback(((6 . 0) deleted "/home/anticrisis/dev/lisp/ml/.fslckout-journal"))
  file-notify--call-handler(#s(file-notify--watch :directory "/home/anticrisis/dev/lisp/ml" :filename nil :callback treemacs--filewatch-callback) (6 . 0) deleted "/home/anticrisis/dev/lisp/ml/.fslckout-journal" nil)
  file-notify--handle-event((6 . 0) (deleted) ".fslckout-journal" 0)
  file-notify--callback-inotify(((6 . 0) (delete) ".fslckout-journal" 0))
  file-notify-handle-event((file-notify ((6 . 0) (delete) ".fslckout-journal" 0) file-notify--callback-inotify))
  funcall-interactively(file-notify-handle-event (file-notify ((6 . 0) (delete) ".fslckout-journal" 0) file-notify--callback-inotify))
  call-interactively(file-notify-handle-event nil [(file-notify ((6 . 0) (delete) ".fslckout-journal" 0) file-notify--callback-inotify)])
  command-execute(file-notify-handle-event nil [(file-notify ((6 . 0) (delete) ".fslckout-journal" 0) file-notify--callback-inotify)] t)
```

**Comment by Alexander-Miller** [comment] 2023-09-30 12:09
Bad git update was to blame. Should be fixed now.

**Closed** 2023-09-30 12:08 UTC

**Comment by anticrisis** [comment] 2023-10-01 00:44
Confirmed, my test case that reliably triggered this problem no longer causes an error. Thank you!
