### ISSUE TITLE
entered--Lisp error: (wrong-type-argument hash-table-p nil)

### ISSUE THREAD

**Issue by cabuda** [Alexander-Miller/treemacs#174] opened 2018-05-02 09:14 UTC
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/Users/didi/.emacs.d/lisp" nil nil)
  treemacs-get-position-of("/Users/didi/.emacs.d/lisp")
  treemacs--goto-button-at("/Users/didi/.emacs.d/lisp/init-treemacs.el")
  treemacs--do-follow("/Users/didi/.emacs.d/lisp/init-treemacs.el" "/Users/didi/.emacs.d/lisp")
  treemacs--follow()
  treemacs--select-window-advice(#<window 3 on *Backtrace*> norecord)
  apply(treemacs--select-window-advice (#<window 3 on *Backtrace*> norecord))
  select-window(#<window 3 on *Backtrace*> norecord)
  page-break-lines--update-display-table(#<window 3 on *Backtrace*>)
  mapc(page-break-lines--update-display-table (#<window 19 on  *Treemacs-Framebuffer-1*> #<window 3 on *Backtrace*>))
  page-break-lines--update-display-tables()
  set-window-buffer(nil #<buffer  *Treemacs-Framebuffer-1*>)
  switch-to-buffer(#<buffer  *Treemacs-Framebuffer-1*>)
  treemacs--setup-buffer()
  treemacs-toggle()
  funcall-interactively(treemacs-toggle)
  call-interactively(treemacs-toggle nil nil)
  command-execute(treemacs-toggle)

When I reboot emacs and run treemacs for the first time, it works well. Then I press Q to kill the treemacs buffer. After that, I run treemacs again, error occurs.

The reason why I want to kill the treemacs buffer is that treemacs could not refresh when I switch to another project. This is a another problem.

**Comment by Alexander-Miller** [comment] 2018-05-03 11:51
First make sure you're using the newest version of treemacs. Then check if this is the same issue as https://github.com/Alexander-Miller/treemacs/issues/166. If not I will need an exact reproduction recipe, preferably with an example of what the project's file system needs to look like to trigger the bug.

> The reason why I want to kill the treemacs buffer is that treemacs could not refresh when I switch to another project.

Define "could not refresh". If you mean it did not update its view to switch to another project, then it is working as intended. Killing the buffer should not be necessary here, just calling `treemacs` again should be enough.

The canonical way to work on multiple projects with the current version is to use multiple frames, as each frame will have its own unique treemacs buffer. I will also soon release a major redesign that allows to render multiple file trees at once.

**Comment by Alexander-Miller** [comment] 2018-06-23 08:21
Bump. Is the issue still around in the most recent treemacs?

**Comment by Compro-Prasad** [comment] 2018-07-20 14:57
@cabuda ^^ ?

**Comment by Compro-Prasad** [comment] 2018-08-29 13:38
@Alexander-Miller You can close this issue. It is not a problem for now.

**Comment by Alexander-Miller** [comment] 2018-08-29 13:40
Yeah, I regularly go through the issue list and close the ones that are inactive. It's about time for another round now.

**Comment by Alexander-Miller** [comment] 2018-08-30 05:05
Closing this due to inactivity.

**Closed by Alexander-Miller** 2018-08-30 05:05 UTC
Labels: Bug

**Comment by Opimenov** [comment] 2019-03-04 15:00
`Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("c:/Users/opimenov/AppData/Roaming/.emacs.d/.cache" nil nil)
  treemacs--apply-deferred-git-state(#<marker at 3 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>)
  apply(treemacs--apply-deferred-git-state (#<marker at 3 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>))
  timer-event-handler([t 23677 15215 632631 nil treemacs--apply-deferred-git-state (#<marker at 3 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>) nil 0])
`

I see similar thing. I have the latest treemacs

**Comment by Alexander-Miller** [comment] 2019-03-04 19:10
> Please help, I really like treemacs and having to delete would be unpleasant.

We'll get to the bottom of this, don't worry. In the meantime you can just disable git-mode.
