### ISSUE TITLE
error: Package `pfuture-1.0' is unavailable

### ISSUE THREAD

**Issue by nickelas** [Alexander-Miller/treemacs#18] opened 2017-06-16 10:19 UTC
When installing treemacs from Melpa I am getting "error: Package `pfuture-1.0' is unavailable".

**Comment by nickelas** [comment] 2017-06-16 10:21
I had treemacs working before by pulling it from github, and also pfuture. Removed both in `.emacs.d/elpa`. Maybe related?

**Comment by Alexander-Miller** [comment] 2017-06-16 16:49
Looks like we're having a dependency problem. Treemacs itself needs emacs 24, but to do async git status fetching it uses pfuture. Pfuture is a wrapper around make-process, which has only been around since emacs 25.
Since IIRC you are on emacs 24 pfuture is "not found" for you. I assume then that you never used git integration? That would explain why it worked for you before.

Unfortunately there's not much to do to make things work with emacs 24. I'll be bumping the required version to make sure the same won't happen to others, but pfuture is an integral part of treemacs. You can either continue going the manual path, or update emacs. emacs 25 has been around for almost a year, and has since received a bug-fix release, so it's not like you'd be running an unstable bleeding edge setup.

**Comment by SerialVelocity** [comment] 2017-06-22 17:49
@Alexander-Miller I'm on emacs 25.2.1 and I'm getting the same error. I'm using the default repos and melpa.

**Comment by Alexander-Miller** [comment] 2017-06-22 19:24
I've run into the same thing with emacs -q now, with any luck I'll also run into the cause.

**Comment by SerialVelocity** [comment] 2017-06-22 20:08
@Alexander-Miller Sorry, forgot to post the cause. I'm using melpa *stable*. This container treemacs but not pfuture.

**Comment by Alexander-Miller** [comment] 2017-06-22 20:42
@SerialVelocity [Try it now.](https://stable.melpa.org/#/pfuture)

**Comment by Alexander-Miller** [comment] 2017-08-15 16:52
This issue still relevant, or can I close here?

**Comment by SerialVelocity** [comment] 2017-08-15 16:57
I haven't had time to try. Feel free to close it and I'll re-open if I encounter the issue in the future

**Closed** 2017-08-15 17:22 UTC
