### ISSUE TITLE
treemacs not playing nicely with perspective

### ISSUE THREAD

**Issue by Randy1Burrell** [Alexander-Miller/treemacs#765] opened 2021-01-12 11:29 UTC
I recently installed perspective and treemacs-perspectives and have been using treemacs for about a year with not much problem. Here is my configuration:

```emacs-lisp
(use-package perspective
  :config
  (setq persp-state-default-file "~/.emacs.d/persp-confs/persp-auto-save")
  (persp-mode)
  :bind (("s-b" . persp-counsel-switch-buffer)
         ("s-M-b" . persp-ivy-switch-buffer)
         ("C-x b" . persp-switch-to-buffer*)
         ("C-x k" . persp-kill-buffer*)))

(use-package persp-mode-projectile-bridge
  :init
  (persp-mode-projectile-bridge-mode 1)
  :config
  (if persp-mode-projectile-bridge-mode
      (persp-mode-projectile-bridge-find-perspectives-for-all-buffers)
    (persp-mode-projectile-bridge-kill-perspectives)))

(global-set-key (kbd "C-x C-b") (lambda (arg)
                                  (interactive "P")
                                  (if (fboundp 'persp-bs-show)
                                      (persp-bs-show arg)
                                    (bs-show "all"))))

(add-hook 'kill-emacs-hook #'persp-state-save)


(use-package treemacs-perspective
  :after treemacs perspective
  :config (treemacs-set-scope-type 'Perspectives))
```

However, now I get these errors when I try to use treemacs to do certain operations like rename a file/directory
```
Error running timer ‘treemacs--follow’: (wrong-type-argument integer-or-marker-p nil) [2 times]
Quit
treemacs-goto-node: Wrong type argument: integer-or-marker-p, nil [4 times]
treemacs--flatten-dirs: Wrong type argument: integer-or-marker-p, nil
treemacs--flatten-dirs: Wrong type argument: integer-or-marker-p, nil
Quit
persp-curr: Lisp nesting exceeds ‘max-lisp-eval-depth’
user-error: No window up from selected window [2 times]
user-error: No window down from selected window [2 times]
Quit
persp-curr: Lisp nesting exceeds ‘max-lisp-eval-depth’
Quit [6 times]
persp-curr: Lisp nesting exceeds ‘max-lisp-eval-depth’
```

**Comment by Alexander-Miller** [comment] 2021-01-12 21:56
> persp-curr: Lisp nesting exceeds ‘max-lisp-eval-depth’

That means there's probably some infinite recursion you are running.

> treemacs--flatten-dirs: Wrong type argument: integer-or-marker-p, nil

These look like a follow up errors because treemacs didn't render things properly.

Unfortunately I cannot reproduce this, so we need to go digging. First of all update treemacs and perspective.

If that doesn't help call `trace-function` on `treemacs-scope->current-scope`. That's the part where treemacs calls `persp-curr` that seems to recurse infinitely. If there's an infinite loop there you'll see the trace buffer fill up with thousands of calls.

In normal use it should be called about 6 times when treemacs is first started and then once whenever it is selected.

Also try things without the projectile bridge.

Finally I have discovered 2 different problems that I should look into as well:

 - The workspace created for the perspective has its projects in the wrong order
 - `Error during redisplay: (run-hook-with-args persp-delete-frame #<frame  *Minibuf-1* 0x55e167d25520>) signaled (wrong-number-of-arguments ((cl-struct-treemacs-scope-shelf-tags t) (scope) "Kill and remove the buffer assigned to the given SCOPE." (let ((shelf (cdr (assoc (or scope (treemacs-scope->current-scope treemacs--current-scope-type)) treemacs--scope-storage)))) (if shelf (progn (progn (let ((buffer (progn (or (progn (and (memq (type-of shelf) cl-struct-treemacs-scope-shelf-tags) t)) (signal 'wrong-type-argument (list 'treemacs-scope-shelf shelf))) (aref shelf 1)))) (if (buffer-live-p buffer) (progn (kill-buffer buffer)))) (progn (or (progn (and (memq (type-of shelf) cl-struct-treemacs-scope-shelf-tags) t)) (signal 'wrong-type-argument (list 'treemacs-scope-shelf shelf))) (let* ((v shelf)) (aset v 1 nil)))) (setq treemacs--scope-storage (-remove-first #'(lambda (it) (equal (car it) scope)) treemacs--scope-storage)))))) 0)
`

**Comment by Randy1Burrell** [comment] 2021-01-13 01:09
Updating treemacs gave these warnings

```
In treemacs-add-bookmark:
treemacs-bookmarks.el:199:38:Warning: treemacs--extract-position called with 1
    argument, but requires 2

In treemacs--imenu-tag-noselect:
treemacs-mouse-interface.el:182:33:Warning: treemacs--extract-position called
    with 1 argument, but requires 2

In treemacs--tag-noselect:
treemacs-mouse-interface.el:208:53:Warning: treemacs--extract-position called
    with 1 argument, but requires 2

In end of data:
treemacs-mouse-interface.el:321:1:Warning: the function
    `project-known-project-roots' is not known to be defined.

In end of data:
treemacs.el:252:1:Warning: the following functions are not known to be
    defined: treemacs--flatten-org-mode-imenu-index,
    treemacs--flatten-imenu-index, treemacs--compare-markdown-tag-paths,
    treemacs--compare-tag-paths
```

Reading the warnings I noticed the message: 

```
treemacs--extract-position called
    with 1 argument, but requires 2
```

That's when I decided to dig deeper and see if [perspectives](https://github.com/nex3/perspective-el) could have been the problem. In the end I found that [persp-mode-projectile-bridge](https://github.com/Bad-ptr/persp-mode-projectile-bridge.el) requires the [persp-mode](https://github.com/Bad-ptr/persp-mode.el) package and had installed it without me knowing. The perspective package readme state that :
> [persp-mode](https://github.com/Bad-ptr/persp-mode.el) - A Perspective fork, which implements perspective sharing between Emacs frames. It also has a different approach to saving state and different configuration options. There has been some interest expressed in merging the two projects. Due to conflicting function names, persp-mode.el and Perspective cannot be installed simultaneously.

 So I delete Both packages and that seems to have fixed it.

**Comment by Alexander-Miller** [comment] 2021-01-13 06:56
> Updating treemacs gave these warnings:

That is stuff I need to fix, but they are just warnigs, and  it's got nothing to do with perspective.

> So I deleted both packages and that seems to have fixed it.

Treemacs has support for both persp and perspective, so I suppose you can switch. I use neither, so I don't know what the difference is, but from treemacs' pov the code for them is basically identical. There's also this: https://github.com/bbatsov/persp-projectile

**Closed** 2021-01-29 09:59 UTC
Labels: Addon:Persp, Bug, Cannot Reproduce
