### ISSUE TITLE
treemacs--follow():   wrong-type-argument errors

### ISSUE THREAD

**Issue by fth86** [Alexander-Miller/treemacs#317] opened 2018-12-21 10:08 UTC
Hi everyone,

I am getting constant wrong-type-argument errors when using the follow mode. I am able to reproduce with a sample project set up as shown here:

![181221_treemacs_bug](https://user-images.githubusercontent.com/13661286/50337002-0e5b7080-0510-11e9-8bec-e47c5e49c48f.png)

Prior to creating this screenshot, I emptied the treemacs-persist file, called (treemacs), and accepted the defaults for project directory and name.

The error occurs when switching windows between the two config.el files. Seems to be related to the <...> suffix on buffer-names. Sorry, I can't say more. Your lisp is rather elegant, but not easy to get my head around.

Finally, by the way - thank you for development, everyone. I am (will be) quite pleased with treemacs (I am sure already).

Best regards,
Florian

**Comment by Alexander-Miller** [comment] 2018-12-21 12:44
I cannot reproduce the issue with a project like yours, so the usual first order of business os to make  sure your treemacs is up-to-date.

One thing I immediately notice is the inconsistent project name. The treemacs buffer shows testproj, the stack trace says /tmp. Any idea how that could've happened? There used to be an issue with a cached value not being invalidated in time that could lead to something like this, but that was fixed back in may.

Otherwise I have to dig around. What do the following pieces of code evaluate to?

```
(treemacs-current-workspace)

(with-current-buffer (treemacs-get-local-buffer)
  (->> (treemacs-current-workspace)
       (treemacs-workspace->projects)
       (-map #'treemacs-project->position)))
```

**Comment by fth86** [comment] 2018-12-21 19:03
>  the usual first order of business os to make sure your treemacs is up-to-date

Sorry, I forgot to mention:  I am on the latest version `20181216.2005`.

> The treemacs buffer shows testproj, the stack trace says /tmp. Any idea how that could've happened?

This was the standard I was presented with on calling `(treemacs)`. Though, I admit, I was playing with some of the top-level management functions for workspace and project management at that time, which might've had some unintended side-effects.

With a clean emacs and treemacs internas i.e. after an emacs restart, I can no longer consistently reproduce this, though since then, it happened some 2-3 more times. I'll keep your code around to run next time it occurs.

**Comment by Alexander-Miller** [comment] 2019-03-14 16:45
Sounds like nothing's happened since december, so let's close this.

**Closed by Alexander-Miller** 2019-03-14 16:45 UTC
