### ISSUE TITLE
Syncthing + treemacs-follow-mode.

### ISSUE THREAD

**Issue by TonCherAmi** [Alexander-Miller/treemacs#570] opened 2019-11-24 15:48 UTC
So I've decided to check [Syncthing](https://syncthing.net/) out today as I have seen many people mention using it successfully for org-mode note sync and was immediately dumbfounded to discover that Emacs freezes completely after I open a synced file, either immediately or after a bit of a delay.

After some fruitless googling I decided to start looking for the issue among the packages I use and after removing treemacs from the startup file the issue disappeared. I then further narrowed down the issue to `treemacs-follow-mode`.

Steps to reproduce:

1. Open a file located inside a directory that is set up to be synced via Syncthing.
2. Enable `treemacs-follow-mode`.
3. Either wait for Emacs to hang or manually rescan the directory via the syncthing interface.
4. Watch Emacs become completely unresponsive (save for reacting to mouse hover over links and such) and start munching away at RAM about 10-20 mb a second.

I'm not sure whether treemacs is really at fault here, but in any case this should at the very least be documented or something as I had no luck googling the issue.

`(treemacs-version)` output: `"v2.6-2019.11.19 @ 26.3"`

EDIT: Just tried it on `2.7`, no luck, the issue is still there.

**Comment by Alexander-Miller** [comment] 2019-11-24 21:40
I doubt this is about syncthing. This is most likely either a bad interaction with some other package or  just a plain bug. Here's what you can try:

 - Make sure it also happens when you start from plain `emacs -Q`
 - Check whether it also happens without follow-mode when you manually call `treemacs-find-file`
 - When emacs is frozen run `kill -12 emacs`. What's the output?

I assume we're looking at a bug in the file finding algorithm. If that's the case I will require a basic reproduction recipe, as the details are influenced by the layout of your files, their names, the nodes treemacs is already showing, and maybe even in which order you closed/opened things. So for easiest debugging you should try and come up with a minimal case where things go wrong, and when that doesn't work I will need to know *exactly* what your file layout looks like.

**Comment by TonCherAmi** [comment] 2019-11-24 22:22
* Tried `emacs -Q` - the issue is there.
* Was not able to reproduce through `treemacs-find-file`, perhaps I'm not hitting the right timing?
* The following:
```
 Debugger entered--Lisp error: (quit)
  file-name-directory("/")
  treemacs-find-file-node("/var/lib/syncthing/notebook/Overview.org" #s(treemacs-project :name "Notebook" :path "/home/me/documents/Notebook" :path-status local-readable))
  treemacs--follow()
  apply(treemacs--follow nil)
  timer-event-handler([t 0 0 200000 nil treemacs--follow nil idle 0])
```

I'll try and come up with something better once I have more time but for now I've had Emacs hang 100%
of the time with the following in my `init.el`:

```elisp
(cd "~/documents/Notebook")

(treemacs)

(find-file "Overview.org")
``` 

when `"~/documents/Notebook"` is symlinked to `/var/lib/syncthing/notebook` which is synced via Syncthing.
I tried linking it to `/tmp/notebook` instead (the contents were exactly the same save for permissions and ownership perhaps) and everything worked fine. So I think its unlikely that Syncthing is not at play here.

**Comment by Alexander-Miller** [comment] 2019-11-24 22:59
The link's the problem. I'm not having the same issue as you are, but I see moving to a symlink gives me trouble as well. I'll dig into this.

**Comment by Alexander-Miller** [comment] 2019-11-24 23:04
Try modifying treemacs-follow-mode.el like this and evaluate the function:
```
modified   src/elisp/treemacs-follow-mode.el
@@ -53,7 +53,7 @@ not visible."
     (treemacs-without-following
      (let* ((treemacs-window (treemacs-get-local-window))
             (current-buffer  (current-buffer))
-            (current-file    (-some-> current-buffer (buffer-file-name) (file-truename))))
+            (current-file    (-some-> current-buffer (buffer-file-name))))
        (when (and treemacs-window
                   current-file
                   (not (s-starts-with? treemacs--buffer-name-prefix (buffer-name current-buffer)))
```

**Comment by TonCherAmi** [comment] 2019-11-25 22:45
Well, that seems to have done the trick, I'm not getting freezes anymore and the mode seems to work okay as well.

**Closed** 2019-11-26 17:32 UTC
Labels: Bug, Feature:File Following

**Comment by Alexander-Miller** [comment] 2019-11-26 17:34
Pushed the fix. It's a revert of #240, but I'm not sure resolving the link really helped, and this issue is a severe bug, while #240 was a mere inconvenience.

**Comment by rileyrg** [comment] 2021-04-10 22:52
symlinks not working with follow mode on my uptodate set up.  I have my ~/.emacs.d/ symlink to a ~/Dropbox/.. path. If I open a file from a bookmark containing the ~/.emacs.d path treemacs doesn't follow.  If I select the file from a file history where it's the fully qualified Dropbox path then treemacs follows.

**Comment by Alexander-Miller** [comment] 2021-04-11 10:30
I got a notification for this ticket. What did I miss?

**Comment by rileyrg** [comment] 2021-04-11 11:48
I deleted a comment because I didn't want to flood you. But follow-mode isn't working when using Dropbox and working through symlinks. In the end, I had to ensure full paths in the treemacs workspace file and also tell emacs to report all buffer names as full "unlinked" paths. It seems to be working better now, and I'll follow up when I investigate more.
