### ISSUE TITLE
Treemacs expands everything when refresh is called:

### ISSUE THREAD

**Issue by yyoncho** [Alexander-Miller/treemacs#1034] opened 2023-06-14 15:11 UTC
Here is a sample code depending on lsp-treemacs.el

```
(setq my/data '((:label "a" :key "1" :icon-literal "")
                (:label "a1" :key "2" :icon-literal "")
                (:label "a2" :key "3" :children ((:label "nb" :key  "ba1" :icon-literal "")
                                                 (:label "nb1" :key "ba2" :icon-literal "")
                                                 (:label "nb2" :key "ba3" :icon-literal ""
                                                         :children
                                                         ((:label "rb" :key  "ra1" :icon-literal "")
                                                          (:label "rb1" :key "ra2" :icon-literal "")
                                                          (:label "rb2" :key "ra3" :icon-literal ""
                                                                  :children))))
                        :icon-literal "")))
(display-buffer
 (lsp-treemacs-render my/data
                      "foo"
                      1
                      "foo"))



```

and then:
```
(with-current-buffer "foo"
  (lsp-treemacs-generic-refresh my/data))
```

Note that when the expansion level passed to treemacs is 0 the issue does not happen.

**Comment by Alexander-Miller** [comment] 2023-06-15 09:48
Looking into it.

**Comment by Alexander-Miller** [comment] 2023-06-15 12:34
I don't think I can reproduce this. Here's what I tried:
- My local treemacs is just the latest master, I currently don't have any dev features running locally.
- I fetched the latest master branch from lsp-treemacs and load it with just `require`, no config
- I ran your code and saw the buffer pop up with the given data
- I hit refresh and the structure remains the same. This is what I see:
![i](https://github.com/Alexander-Miller/treemacs/assets/5951157/813eae5f-d6eb-40a0-97a6-e622f0d8a9b2)

If I understand you correctly then for you treemacs starts expanding the rest of the tree when you refresh. I cannot reproduce that on my end. Do you any differences with my recipe vs yours?

**Comment by Alexander-Miller** [comment] 2023-06-15 14:54
Never mind what I said - I forgot about the 3rd sexp and was refreshing manually. I've reproduced it now locally, no clean-start needed. Whatever's hapening, it is due to `lsp-treemacs-generic-refresh`. I'll have a look what's inside it.

**Comment by Alexander-Miller** [comment] 2023-06-15 17:06
Some internals were using the wrong argument (a marker that still managed to be interpreted as an expand depth value). Problem should be fixed now.

**Closed** 2023-06-15 17:05 UTC
Labels: Bug, Extensions

**Comment by yyoncho** [comment] 2023-06-15 17:49
Thank you for the quick reaction.
