### ISSUE TITLE
[Windows] Treemacs + Tramp + Plink - wrong project path

### ISSUE THREAD

**Issue by LuminaDCIX** [Alexander-Miller/treemacs#824] opened 2021-06-24 03:30 UTC
## Setup

OS: Windows 10
Emacs: Emacs 28.0
Treemacs: Treemacs v2.8

## Description

```bash
[Treemacs] c:/plink:xxxx@xxx:/path/to/my/project is not readable.
```

The issue is the same as #618 

 Is there a solution to this?

**Comment by Alexander-Miller** [comment] 2021-06-28 18:51
I cannot reproduce this problem locally, so I'll need your help with the debugging.

Try applying the following diff and see if it works.
The method is inlined, so you'll have to either recompile, or delete all the byte code
for the change to apply.

```Diff
modified   src/elisp/treemacs-core-utils.el
@@ -452,7 +452,9 @@ In practice this means expand PATH and remove its final slash."
   (inline-letevals (path)
     (inline-quote
      (let (file-name-handler-alist)
-       (-> ,path (expand-file-name) (treemacs--unslash))))))
+       (if (file-remote-p ,path)
+           (-> (treemacs--unslash ,path))
+         (-> ,path (expand-file-name) (treemacs--unslash)))))))
```

Also in general - does `(expand-file-name /plink/path/to/your/project)` do the right thing?

**Comment by LuminaDCIX** [comment] 2021-06-29 02:46
I tried to modify the `treemacs-core-utils.el` file. Deleted all `.elc` files from the `~/.emacs.d/elpa/treemacs-20210606.191` directory and recompiled. This does not seem to work after restarting emacs.

`(expand-file-name "/plink:xxx@xxx:/path/to/my/project/")` returned `"/plink:xxx@xxx:/path/to/my/project/"` itself.

**Comment by Alexander-Miller** [comment] 2021-06-29 20:53
Let's make sure we are on the right track. Does `(treemacs--canonical-path "/plink:xxx@xxx:/path/to/my/project/")` output a broken path?

If yes try using this function:

```Elisp
(defun test-paths ()
  (interactive)
  (let (file-name-handler-alist)
    (message "%s" (treemacs--unslash (expand-file-name (read-directory-name ""))))))
```
It's effectively the same code that treemacs uses. Does it help to leave out the let-binding or some other part?

**Comment by LuminaDCIX** [comment] 2021-06-30 01:10
Both `test-paths` and `(treemacs--canonical-path "/plink:xxx@xxx:/path/to/my/project/")` output a broken path.

But I modified the `test-paths` function to

```emacs-lisp
(defun test-paths ()
  (interactive)
  (let (file-name-handler-alist)
    (message "%s" (read-directory-name ""))))
```

the output is correct.

However, 

```emacs-lisp
(defun test-paths ()
  (interactive)
  (let (file-name-handler-alist)
    (message "%s" (expand-file-name (read-directory-name "")))))
```

returns the broken path  just as the `treemacs--canonical-path` function does.

**Comment by Alexander-Miller** [comment] 2021-06-30 19:55
Almost there. Now we just have to make sure that we can tell when to skip the broken expansion. Try this:

```Elisp
(defun test-paths ()
  (interactive)
  (let ((file-name-handler-alist)
        (file (read-directory-name "")))
    (message
     "%s"
     (if (file-remote-p file)
         (treemacs--unslash file)
       (treemacs--unslash (expand-file-name file))))))
```

**Comment by LuminaDCIX** [comment] 2021-07-01 04:33
Strangely enough the new `test-paths` still returns the broken path.

I tried `M-: (file-remote-p "/plink:xxx@xxx:/path/to/my/project/")` and the return is not nil;

But when I run

```emacs-lisp
(defun test-paths ()
  (interactive)
  (let ((file-name-handler-alist)
        (file (read-directory-name "")))
    (message
     "%s"  (file-remote-p file))))
```

It returns nil;

Is it possible that this is a bug in emacs on windows?

**Comment by Alexander-Miller** [comment] 2021-07-01 09:27
Try it without the file-name-handler:

```Elisp
(defun test-paths ()
  (interactive)
  (let ((file (read-directory-name "")))
    (message
     "%s"  (file-remote-p file))))
```

**Comment by LuminaDCIX** [comment] 2021-07-02 05:35
```emacs-lisp
(defun test-paths ()
  (interactive)
  (let ((file (read-directory-name "")))
    (message
     "%s"
     (if (file-remote-p file)
         (treemacs--unslash file)
       (treemacs--unslash (expand-file-name file))))))
```

Now the function works correctly after remove `file-name-handler`.

**Comment by Alexander-Miller** [comment] 2021-07-05 19:45
I've pushed the fix now. Let me know if it works.

**Closed** 2021-07-05 19:44 UTC
Labels: Bug, Feature:Workspaces
