### ISSUE TITLE
counsel-ag usually fails when treemacs is open

### ISSUE THREAD

**Issue by landshark666** [Alexander-Miller/treemacs#19] opened 2017-06-21 21:30 UTC
I'm using counsel-ag for searching. When treemacs is open, it usually fails with `Wrong type argument: stringp, nil`.  If I toggle treemacs off, counsel-ag works again.  From the stack trace, the filename obtained from counsel-git-grep-action seems to be coming back as nil when the tree is open. Maybe some kind of advice is interfering with it?

Here's the stacktrace:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil "/home/XXX/.emacs.d/")
  counsel-git-grep-action(#("lisp-versioned/use-package/README.md:28:(use-package foo" 0 36 (face compilation-info) 37 39 (face compilation-line-number)))
  ivy-call()
  ivy-read("ag" #[257 "\302	\300\242#\207" [(nil) counsel-ag-base-command counsel-ag-function] 5 "\n\n(fn STRING)"] :initial-input nil :dynamic-collection t :keymap (keymap (27 keymap (113 . counsel-git-grep-query-replace)) (12 . counsel-git-grep-recenter)) :history counsel-git-grep-history :action counsel-git-grep-action :unwind #[0 "\300 \210\301 \207" [counsel-delete-process swiper--cleanup] 1] :caller counsel-ag)
  counsel-ag()
  funcall-interactively(counsel-ag)
  call-interactively(counsel-ag)
  hydra--call-interactively-remap-maybe(counsel-ag)
  (progn (setq this-command (quote counsel-ag)) (hydra--call-interactively-remap-maybe (function counsel-ag)))
  my/hydra-grep/counsel-ag-and-exit()
  funcall-interactively(my/hydra-grep/counsel-ag-and-exit)
  call-interactively(my/hydra-grep/counsel-ag-and-exit nil nil)
  command-execute(my/hydra-grep/counsel-ag-and-exit)
```

**Comment by Alexander-Miller** [comment] 2017-06-22 10:58
I don't use any of the ivy/hydra packages the stacktrace, so I need you to give me a full recipe:
 * What packages do I install?
 * How are they configured?
 * What's that custom hydra look like, how do I call and use it?
 * What string do you search for?
 * What's the treemacs window showing?

**Comment by landshark666** [comment] 2017-06-22 19:33
The minimal way I could reproduce it was as follows.

Make a directory, I called it `bug`.  Put the following in `bug/bug.el`.  Adjust the paths as necessary.  I have a package cache setup with the use-package package in it. You can probably replace that with a suitable call to package-install.

```
(require 'package)
(add-to-list 'load-path "~/.emacs.d/lisp-versioned/use-package")
(setq package-user-dir "~/.emacs.d/lisp/package-cache")

(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(when (< emacs-major-version 24)
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
(require 'use-package)

(use-package projectile :ensure t)
(use-package swiper :ensure t)
(use-package treemacs :ensure t :defer t
  :config (progn
            (setq treemacs-header-function #'treemacs--create-header
                  treemacs-follow-after-init t
                  treemacs-width 35
                  treemacs-indentation 2
                  treemacs-git-integration t
                  treemacs-change-root-without-asking nil
                  treemacs-sorting 'alphabetic-desc
                  treemacs-show-hidden-files t
                  treemacs-never-persist nil)
            (treemacs-follow-mode t)
            (treemacs-filewatch-mode t))
  :bind (:map global-map
              ([f4] . treemacs-toggle)
              ("C-<f4>" . treemacs-projectile)))
```

Now create `bug/test1.txt` with:

```
test 1
test 2
test 3
test 4
test 5
test 6
```

Create `bug/test2.txt` with the exact same contents as `test.txt`.

In the `bug` directory start emacs with `emacs -Q -load bug.el`

Start treemacs with `F4`.  Then run counsel-ag with `M-x counsel-ag` and type `test`. Select the first entry. It works.  Run the same counsel-ag command with test as input a few more times, eventually it fails with  `Wrong type argument: stringp, nil`.

If I kill or close treemacs, it works again.

**Comment by Alexander-Miller** [comment] 2017-06-22 20:37
Took me a while to see that counsel is its own package, but I've the issue reproduced now. The cause seems to be in follow-mode. To make it work I need to advise select-window. This then somehow interferes with counsel's window selection. I suppose I'll need to clear this up with @abo-abo. (He'll get a notification if I @ mention him, right?).

In the meantime there 2 things for you to do:
 * dont use treemacs-follow-mode and call treemacs-find-file manually when needed
 * use the following untested workaround (at least it does eliminate the conflict):
```
(defun counsel-ag-no-follow (&rest args)
  (interactive)
  (treemacs--without-following
   (apply #'counsel-ag args))
  (treemacs-find-file))
```
@abo-abo: Can you please tell me more about how and when counsel-ag does window selection? Something non-trivial seems to be happening for treemacs to run into trouble here.
On the side of treemacs I'm running a simple bit of advice after select-window which looks at the file in the selected window and then selects it in the treemacs window if the window is visible.

**Comment by abo-abo** [comment] 2017-06-23 11:56
> Can you please tell me more about how and when counsel-ag does window selection?

`counsel-ag` records the window from which it was called. Then it aims to display the results in the same window.

**Comment by Alexander-Miller** [comment] 2017-06-24 15:15
@landshark666 @abo-abo 
Good news, everyone! 
I've found the root of the problem, and it can easily be fixed without requiring me to wrap half of counsel.el into the no-follow macro. I use text search as an optimization when looking for a given file to select, but, lacking experience with part of emacs. I neglected to wrap that call with save-match-data. Changing the match data here then interfered with counsel's search.

I'll make sure this doesn't happen anywhere else in treemacs, and then push the fix in 1 or 2 days.

I also quite like counsel-ag's interface and performance, so at least this bug report got you a new user.

**Comment by abo-abo** [comment] 2017-06-24 18:56
Glad it's solved:)

**Comment by Alexander-Miller** [comment] 2017-06-25 22:15
@landshark666 
Issue should be fixed with https://github.com/Alexander-Miller/treemacs/commit/7a03e30648a74d056a4cc31642b4e045a1ff6941
Let me know if it works for you.

**Comment by landshark666** [comment] 2017-06-26 02:23
Excellent! I'll give it a try when I get into work on Monday.

**Comment by landshark666** [comment] 2017-06-26 14:06
@Alexander-Miller 
It seems to be working. Thank you for the fix! When you push the fix, will you also be pushing up to Melpa?

**Comment by Alexander-Miller** [comment] 2017-06-26 14:14
That's done automatically - melpa builds the master branch of its packages every ~4 hours, so the fix is already up.

**Closed by Alexander-Miller** 2017-06-26 14:14 UTC
