### ISSUE TITLE
Native compiled Treemacs can't find python scripts

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#643] opened 2020-04-07 06:52 UTC
I'm testing out the [`nativecomp`](https://akrl.sdf.org/gccemacs.html) Emacs branch, that provides compilation of Emacs Lisp to native code, thus making Emacs way more performant. Overall impression is really good, but I've found one problem, that compiled files go into `eln-arch-os-hash` directory, e.g. `eln-x86_64-pc-linux-gnu-XXXXXXXXX`, and then Emacs loads those instead of `.el` or `.elc`. This works fine for all emacs-lisp packages, but not for Treemacs, because Treemacs uses some python scripts, and because compiled files are being loaded from the other directory, Treemacs can't find those:

```
[Treemacs] treemacs-git-status.py wrote to stderr: /usr/bin/python3: can't open file '/home/andreyorst/.config/emacs/elpa/treemacs-20200405.1052/eln-x86_64-pc-linux-gnu-ca82f1e5d8ab0204/src/scripts/treemacs-git-status.py': [Errno 2] No such file or directory
```

`treemacs-git-status.py` is located where all `.el` files are, so copying it into `eln-....` directory fixes the issue, until next recompilation (e.g. package update)

Maybe there is a way to properly provide correct paths for python scripts without relying on from where `.el`/`.elc`/`.eln` file was actually loaded?

I'm not sure maybe this should be discussed with main `gccemacs` dev though, and changed so `.eln` files follow the convention of `.elc` file placement, but it seems they don't use GitHub

**Comment by yyoncho** [comment] 2020-04-07 07:06
There are a lot of packages that use the load path to calculate relative paths. IMO this should be either fixed (e. g. by faking load-path) or it should be manifested as breaking change. Definitely this should be reported to Andrea.

**Comment by andreyorst** [comment] 2020-04-07 07:32
Understood. Should I keep this issue open until it's fixed in `native-comp`?

**Comment by AndreaCorallo** [comment] 2020-04-07 11:34
No idea how treemacs works in details, but if relies on is using `load-file-name` then the issue is this:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=40099

If that's the case is already on my todolist.  Please report if the issue is a different one.

Thanks
  Andrea

**Comment by Alexander-Miller** [comment] 2020-04-07 19:08
>  No idea how treemacs works in details, but if relies on is using load-file-name then the issue is this:

It's the same issue. Treemacs looks at load-file-name to determine the location of its python scripts and icons.

> Understood. Should I keep this issue open until it's fixed in native-comp?

Let's close this. Andrea is already on it, and as promising as native compilation is, for now it exists only as a feature branch, which is much too early for a package like treemacs to be worrying about it.

Besides you will not miss out by not compiling treemacs. Based on my own naive benchmarks (opening a single very large directory) native compilation offers absolutely no advantage over stand byte compilation, presumably because all the heavy lifting in treemacs already happens inside C primitives.

> so copying it into eln-.... directory fixes the issue, until next recompilation (e.g. package update)

It'd be easier to change the variables to point to the right location, there's only 3 or 4 of them at most.

**Closed by Alexander-Miller** 2020-04-07 19:08 UTC

**Comment by andreyorst** [comment] 2020-04-07 19:26
Understood, thanks!

вт, 7 апр. 2020 г., 22:08 Alexander-Miller <notifications@github.com>:
