### ISSUE TITLE
I keep getting this error: error "‘recenter’ing a window that does not display current-buffer."

### ISSUE THREAD

**Issue by gjm** [Alexander-Miller/treemacs#363] opened 2019-02-20 15:15 UTC
I keep getting this error:
```
Error running timer ‘treemacs--process-file-events’: (error "‘recenter’ing a window that does not display current-buffer.")
```
Can't really pinpoint what triggers it. What can I do to debug this issue?

**Comment by Alexander-Miller** [comment] 2019-02-20 16:05
First make sure your treemacs is up-to-date. I did some work on the recenter parts recently, you might have caught a bad version.

> Can't really pinpoint what triggers it.

Not surprising, that part is a couple macros deep. Try debug-on-error. If that won't work try `(setf debug-on-message (rx (1+ any) "treemacs--process-file-events" (1+ any)))`.

**Comment by gjm** [comment] 2019-02-20 16:10
I'm using the latest version, I think: `treemacs-20190219.1558`.

I've tried `debug-on-error` and got this:

```
  recenter()
  treemacs--maybe-recenter(on-distance)
  treemacs--expand-root-node(#<marker at 3 in  *Treemacs-Framebuffer-1*>)
  treemacs--do-refresh(#<buffer  *Treemacs-Framebuffer-1*>
[cl-struct-treemacs-project "siiue"
"/home/gjm/work/siiue/siiue2020/src/siiue"])
  treemacs--recursive-refresh()
  treemacs--process-file-events()
  apply(treemacs--process-file-events nil)
  timer-event-handler([t 23661 31567 780260 nil
treemacs--process-file-events nil nil 859000])
```

Gonçalo Marrafa

**Comment by Alexander-Miller** [comment] 2019-02-20 16:14
I think I know what to do. In the meantime you can set `treemacs-recenter-after-project-expand` to nil.

**Comment by gjm** [comment] 2019-02-20 16:42
Will do. Thanks-

**Comment by Alexander-Miller** [comment] 2019-03-02 22:41
Should be fixed now. Please verify.

**Comment by seagle0128** [comment] 2019-03-03 04:48
@Alexander-Miller I got this error now.

```elisp
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/Users/vincent/.emacs.d/.cache" nil nil)
  treemacs--apply-deferred-git-state(#<marker at 22 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>)
  apply(treemacs--apply-deferred-git-state (#<marker at 22 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>))
  timer-event-handler([t 23675 23651 785673 nil treemacs--apply-deferred-git-state (#<marker at 22 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>) nil 0])
```

**Comment by Alexander-Miller** [comment] 2019-03-03 10:53
@seagle0128 I cannot reproduce that. That part of the code involves plenty of hash tables, can you jump into the debugger and tell me which line of `treemacs--apply-deferred-git-state` the error occurs in?

**Comment by seagle0128** [comment] 2019-03-03 16:10
@Alexander-Miller it's line 469.

**Comment by Alexander-Miller** [comment] 2019-03-03 21:01
You sure? [That line isn't doing anything hash-related](https://github.com/Alexander-Miller/treemacs/blob/bd7767162a30fe939d0d432e6a6bc949860c0aa9/src/elisp/treemacs-rendering.el#L469).

**Comment by seagle0128** [comment] 2019-03-04 07:06
@Alexander-Miller It should be https://github.com/Alexander-Miller/treemacs/blob/bd7767162a30fe939d0d432e6a6bc949860c0aa9/src/elisp/treemacs-rendering.el#L472 now.

**Comment by Alexander-Miller** [comment] 2019-03-04 16:09
What is the result you expect to see - does the error happen everywhere or only files that are (not) under version control, does it affect only a part of a project, or all of it?

It looks like this nil error can occur when the git process fails. I can close that gap, but it that'd be removing just a symptom, and not the cause. What does the follow code output for you:
```Lisp
(-> "/dir/where/error/happens"
    (treemacs--git-status-process-function)
    (pfuture-await-to-finish))
```

**Comment by seagle0128** [comment] 2019-03-04 18:08
@Alexander-Miller After upgrading the package, I didn't see this error. I will keep on my eyes. Thanks!

**Comment by Alexander-Miller** [comment] 2019-03-04 19:04
I did recently switch up the git-mode implementation in https://github.com/Alexander-Miller/treemacs/commit/871069296400425c7ebe84dddbc4b841d40e39b0, so maybe the transition wasn't quite smooth for you. Did you restart emacs after the update that brought on the git problem?

@Opimenov how about you?

**Comment by Opimenov** [comment] 2019-03-04 19:07
yes I did.

Best Regards
Alex Pimenov

________________________________

**Comment by Alexander-Miller** [comment] 2019-03-04 19:09
What about the test code in https://github.com/Alexander-Miller/treemacs/issues/363#issuecomment-469310284 ?

**Comment by Opimenov** [comment] 2019-03-04 19:15
`Traceback (most recent call last):
File \"~/.emacs.d/elpa/treemacs-20190303.1245/treemacs-git-status.py\," line 10 in <module>
STDOUT = sys.stdout.buffer
AttributeError: 'file' object has no attribute 'buffer'`

**Comment by Alexander-Miller** [comment] 2019-03-04 19:18
2 things:

1. You should try it with a directory, not a file.
2. The error looks like a python version problem. The python script needs python 3, if you have it installed you can just set the value of `treemacs-python-executable`.

**Comment by Opimenov** [comment] 2019-03-04 19:26
1. trying with a dir produced the same result.
2. setting python executable to python3 solved the problem. Let me know if I could help updating docs. 
Thanks.

**Comment by Alexander-Miller** [comment] 2019-03-04 20:39
Sure, if you want to help you can give https://github.com/Alexander-Miller/treemacs/issues/370 a go.

**Comment by Alexander-Miller** [comment] 2020-04-25 15:47
Housekeeping.

**Closed by Alexander-Miller** 2020-04-25 15:47 UTC
Labels: Bug, Feature:Filewatch
