### ISSUE TITLE
Black icon background color

### ISSUE THREAD

**Issue by DougBeney** [Alexander-Miller/treemacs#303] opened 2018-11-05 14:06 UTC
![Screenshot](https://i.imgur.com/TPiWzIB.png)

I am having the same issue as https://github.com/Alexander-Miller/treemacs/issues/148 again but this time with a black background color.

- Treemacs v2.2.2-2018.11.03 @ 26.1
- Ubuntu 18.04. (KDE Neon to be specific, but it is based off of Ubuntu 18.04)

## Notes:

- Evaluating `treemacs--setup-icon-background-colors` does not solve the problem.
- No Treemacs warning in Messages buffer
- `(face-attribute 'default :background nil t)` displays the proper color for my theme
- `(face-attribute 'hl-line :background nil t)` displays the proper color for my theme
- This issue occurs with  all theme I have tried.
- If you go into `customize-themes`, select a new theme, then go back to your other theme it will be fixed until you quit and re-open Emacs.

## Emacs Customize

Here is the customize section of my Emacs config

```lisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes (quote (dracula)))
 '(custom-safe-themes
	 (quote
		("aaffceb9b0f539b6ad6becb8e96a04f2140c8faa1de8039a343a4f1e009174fb" default))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by Alexander-Miller** [comment] 2018-11-05 16:31
> Evaluating treemacs--setup-icon-background-colors does not solve the problem.

That is because this function is called every time treemacs-mode is entered, so I make sure that I don't loop over the ever-growing number of icons unless I have to. There's a check to make sure that the colors drawn from your current theme are actually different than the colors that were found the last time around. How they can be the same while you still see the wrong thing is beyond me.

Guess I'll need to try a different strategy. When you are seeing the wrong colors, what is the value of `treemacs-icon-css`?

And just to be sure: are `treemacs--selected-icon-background` and `treemacs--not-selected-icon-background` set to the right colors for your theme?

**Comment by Alexander-Miller** [comment] 2018-11-05 16:32
Try this version:
```

(defun treemacs--setup-icon-background-colors (&rest _)
  "Align icon backgrounds with current theme.
Fetch the current theme's background & hl-line colors and inject them into
`treemacs--created-icons'. Also called as advice after `load-theme', hence the
ignored argument."
  (let* ((default-background (face-attribute 'default :background nil t))
         (hl-line-background (face-attribute 'hl-line :background nil t))
         (icon               (car (treemacs--created-icons)))
         (icon-background    (image-property (get-text-property 0 'img-unselected icon) :background))
         (icon-hl-background (image-property (get-text-property 0 'img-selected icon) :background)))
    (when (eq default-background 'unspecified-bg)
      (setq default-background "#2d2d31"))
    ;; make sure we only change all the icons' colors when we have to
    (unless (and (string= default-background icon-background)
                 (string= hl-line-background icon-hl-background))
      (--each (treemacs--created-icons)
        (progn
          (treemacs--set-img-property
           (get-text-property 0 'img-selected it)
           :background treemacs--selected-icon-background)
          (treemacs--set-img-property
           (get-text-property 0 'img-unselected it)
           :background treemacs--not-selected-icon-background))))))
```

**Comment by Alexander-Miller** [comment] 2018-11-19 07:52
Bump?

**Comment by Alexander-Miller** [comment] 2018-11-21 06:32
I've reproduced the problem, and the fix works for me, so I've pushed it to master now.

**Comment by seblemaguer** [comment] 2019-09-15 08:08
Hello,

I moved from 2.6 from melpa-stable to the master branch because #480 is still causing problem on the stable version and now I am facing the problem too. I am investigating a little bit more.

**Comment by gugutz** [comment] 2019-10-29 15:11
any news on this? im also having this problem with the black bg on my icons

**Comment by gugutz** [comment] 2019-10-29 15:16
> any news on this? im also having this problem with the black bg on my icons

im sorry for this  bump. its actually working now, my bad. :|

**Comment by seblemaguer** [comment] 2020-01-30 16:20
This works for me two since around december.

**Comment by sarna** [comment] 2020-03-26 10:58
I'm affected by this now, Emacs 26.3.

What fixed it was changing the image mode from indexed to RGB in GIMP. All the images with indexed mode rendered black backgrounds for me.

**Comment by Alexander-Miller** [comment] 2020-04-17 10:15
I've moved every single icon to RGB now. Let me know if that helps.

**Comment by Alexander-Miller** [comment] 2020-04-17 11:03
Never mind, moving to RGB darkened the icons on my end, I've reverted the change for now.

**Comment by Alexander-Miller** [comment] 2020-04-17 11:14
I've used imagemagick for the conversion with `mogrify -colorspace rgb $file` instead of gimp to get them all at once. Without this automation we'll have to go on a case by case basis, so please let me know which icons need changing.

**Comment by Alexander-Miller** [comment] 2020-04-24 09:03
Just managed to run into a whole lot of black backgrounds myself. Looks like this only happens when your emacs has no imagemagick support (You can check with `(image-type-available-p 'imagemagick)`).

Now that I know how to reproduce things I'll start fixing the icons in gimp now. Might take me a while though because it looks like most of treemacs' 150+ icons are affected.

**Closed** 2020-04-25 15:41 UTC

**Comment by ksjogo** [comment] 2020-05-13 00:20
I have a similiar issue, where the background value of #3f3f3f seems to be picked up in treemacs for the treemacs--not-selected-icon-background value, but the rendering is actually done as #505050:
![Screenshot 2020-05-13 at 02 19 40](https://user-images.githubusercontent.com/699858/81757805-593ca600-94c0-11ea-98f6-af6662887ea9.png)
(image-type-available-p 'imagemagick) returns t

**Comment by Alexander-Miller** [comment] 2020-05-16 12:47
@ksjogo What do the followings pieces of code output?

 - `(format "%s %s" treemacs--selected-icon-background treemacs--not-selected-icon-background)`
 - `(face-attribute 'default :background nil t)`
 - `(face-attribute 'hl-line :background nil t)`
 - `(prin1-to-string (treemacs-get-icon-value 'dir-open))`
 - `(treemacs--get-img-property (get-text-property 0 'img-unselected (treemacs-get-icon-value 'dir-open)) :background)`
 - `(treemacs--get-img-property (get-text-property 0 'img-selected (treemacs-get-icon-value 'dir-open)) :background)`

**Comment by ksjogo** [comment] 2020-05-17 21:11
```
"#3a3a3a #3f3f3f"
"#3f3f3f"
"#3a3a3a"
"#(\"  \" 0 1 (display (image :type imagemagick :file \"/Users/johannes/.emacs.d/elpa/develop/treemacs-20200506.1600/icons/default/vsc/dir-open.png\" :scale 1 :ascent center :width 22 :height 22 :background \"#3f3f3f\") img-selected (image :type imagemagick :file \"/Users/johannes/.emacs.d/elpa/develop/treemacs-20200506.1600/icons/default/vsc/dir-open.png\" :scale 1 :ascent center :width 22 :height 22 :background \"#3a3a3a\") img-unselected (image :type imagemagick :file \"/Users/johannes/.emacs.d/elpa/develop/treemacs-20200506.1600/icons/default/vsc/dir-open.png\" :scale 1 :ascent center :width 22 :height 22 :background \"#3f3f3f\")))"
"#3f3f3f"
"#3a3a3a"
```

**Comment by Alexander-Miller** [comment] 2020-05-18 11:25
All those values are correct. I see absolutely no reason for the #505050 to be there. Let's check if there is something wrong with change detection. Kill the treemacs buffer and eval this:

```Elisp
(defun treemacs--setup-icon-background-colors ()
  (setf treemacs--selected-icon-background "red"
        treemacs--not-selected-icon-background "green")
  (dolist (theme treemacs--themes)
    (treemacs--maphash (treemacs-theme->gui-icons theme) (_ icon)
      (treemacs--set-img-property
       (get-text-property 0 'img-selected icon)
       :background treemacs--selected-icon-background)
      (treemacs--set-img-property
       (get-text-property 0 'img-unselected icon)
       :background treemacs--not-selected-icon-background))))
```
Does that work as expected:
![colors](https://user-images.githubusercontent.com/5951157/82207929-ed689c00-990a-11ea-900d-280166105957.png)

**Comment by ksjogo** [comment] 2020-05-18 22:53
They change to green and red, yes.
Even setting 3f3f3f directly there will result in 505050 in the final rendering though.

**Comment by Alexander-Miller** [comment] 2020-05-19 16:12
Then I have absolutely no idea why such a shift would occur.

If it really is just a shift you will have the tools for manual correction with https://github.com/Alexander-Miller/treemacs/issues/663, but that's all I can do here.

**Comment by ksjogo** [comment] 2020-05-19 18:23
Yeah, very weird things happening,  I will try to manually precalculate the shift. 
Thank you for your support and treemacs Alexander.

**Comment by BlindingDark** [comment] 2020-08-19 03:40
I found that these problem icons are all 16-bit png, so I used the following command to convert these icons to 8-bit
```
cd ~/.emacs.d/elpa/treemacs-xxxxxxx/icons
fd ".png$" ./ --type file | xargs identify | rg 16-bit | awk '{print $1}' | xargs -I {} convert {} -depth 8 {}
```

Everything is normal after the conversion.
