### ISSUE TITLE
Treemacs got a weird error when trying to use

### ISSUE THREAD

**Issue by VisionaryAppDev** [Alexander-Miller/treemacs#302] opened 2018-11-01 15:33 UTC
When I am trying to open Treemacs using `treemacs` command, then it prompt me to input my directory while in Message Buffer, it print the below error message:

> [Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.
> treemacs-do-add-project-to-workspace: Invalid function: treemacs-is-path

I am using Emacs GNU version 26 and please check the below configuration that I have:

`(use-package` treemacs
  :ensure t
  :defer t
  :config
  (progn
    (setq treemacs-collapse-dirs              (if (executable-find "python") 3 0)
          treemacs-deferred-git-apply-delay   0.5
          treemacs-display-in-side-window     t
          treemacs-file-event-delay           5000
          treemacs-file-follow-delay          0
          treemacs-follow-after-init          t ;; When t follow the currently selected file after initializing the treemacs buffer, regardless of treemacs-follow-mode setting.
          treemacs-follow-recenter-distance   0.1
          treemacs-goto-tag-strategy          'refetch-index
          treemacs-indentation                2
          treemacs-indentation-string         " "
          treemacs-is-never-other-window      nil ;; Prevents treemacs from being selected with other-window.
          treemacs-no-png-images              nil ;; When non-nil treemacs will use TUI string icons even when running in a GUI.
          treemacs-project-follow-cleanup     nil ;; When non-nil treemacs-follow-mode will keep only the current project expanded and all others closed.
          treemacs-persist-file               (expand-file-name ".appdata/.cache/treemacs-persist" user-emacs-directory)
          treemacs-recenter-after-file-follow nil
          treemacs-recenter-after-tag-follow  nil
          treemacs-show-hidden-files          t
          treemacs-silent-filewatch           t
          treemacs-silent-refresh             t
          treemacs-sorting                    'alphabetic-desc
          treemacs-space-between-root-nodes   t
          treemacs-tag-follow-cleanup         t
          treemacs-tag-follow-delay           1.5
          treemacs-width                      35
	  treemacs-max-git-entries 5000)
    (define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action)
    ;; The default width and height of the icons is 22 pixels. If you are
    ;; using a Hi-DPI display, uncomment this to double the icon size.
    ;;(treemacs-resize-icons 44)
    
    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode t)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null (executable-find "python3"))))
      (`(t . t)
       (treemacs-git-mode 'extended))
      (`(t . _)
       (treemacs-git-mode 'simple))))
  :bind
  (:map global-map
        ("M-0"       . treemacs-select-window)
        ("C-x t 1"   . treemacs-delete-other-windows)
        ("C-x t t"   . treemacs)
        ("C-x t B"   . treemacs-bookmark)
        ("C-x t C-t" . treemacs-find-file)
        ("C-x t M-t" . treemacs-find-tag)))

(use-package treemacs-evil
  :after treemacs evil
  :ensure t)

(use-package treemacs-projectile
  :after treemacs projectile
  :ensure `t)`

**Comment by Alexander-Miller** [comment] 2018-11-01 16:41
> [Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.
treemacs-do-add-project-to-workspace: Invalid function: treemacs-is-path

Those are 2 different errors and I don't know what the second one is about, so let's start with the first.

That message means something went wrong when loading your projects. They are saved in `treemacs-persist-file` which defaults to ~/.emacs.d/.cache/treemacs-persist. What does the content of that file look like?

**Comment by VisionaryAppDev** [comment] 2018-11-02 13:41
Hi, I check the file and found the following data:
```* Default Workspace```

And after updated the plugin today, it produces another data:

```
* Default Workspace
** edu
-  path :: /home/test/edu
```

And in the Message buffer, it produces below error: 
```
[Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.
Saving file /home/.emacs.d/.appdata/.cache/treemacs-persist...
Wrote /home/.emacs.d/.appdata/.cache/treemacs-persist

```

And when I click on the icon, it produces below error but it did not expand any files nor directories in the directory I click at all.
```
treemacs--git-status-parse-function: Invalid read syntax: ". in wrong context"
user-error: No more buttons [2 times]
```


*NOTE* before update to the newer version, there isn't any icon after the path was add.

**Comment by Alexander-Miller** [comment] 2018-11-02 14:40
> \-  path :: /home/test/edu

Is this entirely accurate? The last line should lead with a space.

> treemacs--git-status-parse-function: Invalid read syntax: ". in wrong context"

That is something else. What is the output of `git status --porcelain --ignored .` when it's run in your edu project?

**Comment by VisionaryAppDev** [comment] 2018-11-03 17:15
Ok, I have rechecked and I missed the space. Here is the correct format:
```
* Default Workspace
** edu
 - path :: /home/test/edu
```

When I run `git status --porcelain --ignored` from the project root dir, it got the following output:
```
 M .classpath
 M .directory
 M .gradle/4.4/fileHashes/fileHashes.bin
 M .gradle/4.4/fileHashes/fileHashes.lock
 M .gradle/4.4/taskHistory/taskHistory.bin
 M .gradle/4.4/taskHistory/taskHistory.lock
 M .gradle/buildOutputCleanup/buildOutputCleanup.lock
 M .gradle/buildOutputCleanup/outputFiles.bin
 M .idea/sonarlint/issuestore/0/c/0c747810fab07ba60641f3582d9e275a410a3a77
 D .idea/sonarlint/issuestore/c/7/c712fb16aaa362c37e31295eba5730e996d5980e
 M .idea/sonarlint/issuestore/index.pb
 M .idea/workspace.xml
 M .pmd
 M .project
 M .settings/org.eclipse.buildship.core.prefs
 M .settings/org.sonarlint.eclipse.core.prefs
 D bin/.gitignore
 M build.gradle
 M src/main/java/com/cc/edu/dto/post/EducationPost.java
 M src/main/java/com/cc/edu/service/api/account/AccountService.java
 M src/main/java/com/cc/edu/service/imp/account/SessionManagerService.java
 M src/main/java/com/cc/edu/web/controller/HomeController.java
 M src/main/java/com/cc/edu/web/controller/post/PostController.java
 M src/main/webapp/RESOURCES/config/bean/dbmapper.xml
 M src/main/webapp/RESOURCES/config/system/context-security.xml
 D src/main/webapp/RESOURCES/log/archived/debug.2018-06-30.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-01.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-02.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-03.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-04.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-05.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-06.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-07.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-08.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-09.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-10.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-17.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-21.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-22.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-24.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-26.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-28.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-29.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-30.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-30.1.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-30.2.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-30.3.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-07-31.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-01.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-02.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-04.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-05.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-06.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-07.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-08.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-09.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-10.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-11.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-12.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-13.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-14.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-15.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-16.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-18.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-28.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-30.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-08-31.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-09-01.0.log
 D src/main/webapp/RESOURCES/log/archived/debug.2018-09-02.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-06-30.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-01.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-02.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-03.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-05.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-06.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-07.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-08.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-10.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-17.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-21.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-22.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-28.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-29.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-07-30.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-01.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-04.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-05.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-06.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-07.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-08.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-09.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-10.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-11.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-13.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-14.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-15.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-28.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-30.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-08-31.0.log
 D src/main/webapp/RESOURCES/log/archived/error.2018-09-01.0.log
 M src/main/webapp/RESOURCES/log/debug.log
 M src/main/webapp/RESOURCES/log/error.log
 M src/main/webapp/RESOURCES/views/fragments/accounts/accounts-login.html
 M src/main/webapp/RESOURCES/views/fragments/posts/posts-course.html
 M src/main/webapp/RESOURCES/views/layouts/default.html
 D src/main/webapp/USER_DATA/2018-09-02/1103287448.png
 D src/main/webapp/USER_DATA/2018-09-02/1148319002.png
 D "src/main/webapp/USER_DATA/2018-09-02/1259550780.Screenshot from 2018-05-30 21-42-58.png"
 D src/main/webapp/USER_DATA/2018-09-02/2064639958.png
 D src/main/webapp/USER_DATA/2018-09-02/2077008999.png
 D src/main/webapp/USER_DATA/2018-09-02/3229730262.png
 D src/main/webapp/USER_DATA/2018-09-02/3334161898.png
 D src/main/webapp/USER_DATA/2018-09-02/3621472288.png
 D src/main/webapp/USER_DATA/2018-09-02/3898813725.png
 D src/main/webapp/USER_TEMP/2018/09/03/1216715947
 D src/main/webapp/USER_TEMP/2018/09/03/1621067517
 D src/main/webapp/USER_TEMP/2018/09/03/3111313555
?? .idea/sonarlint/issuestore/1/
?? bin/main/
?? src/main/java/com/cc/edu/dto/other/#PostDUImage.java#
?? src/main/java/com/cc/edu/dto/other/DUImage.java
?? src/main/java/com/cc/edu/dto/other/PostDUImage.java
?? src/main/java/com/cc/edu/dto/other/TempDUImage.java
?? src/main/java/com/cc/edu/dto/other/UserDUImage.java
?? src/main/java/com/cc/edu/web/controller/#ImageHandlerController.java#
?? src/main/java/com/cc/edu/web/controller/ImageHandlerController.java
?? src/main/java/com/cc/edu/web/controller/~/
?? src/main/webapp/RESOURCES/log/archived/debug.2018-10-08.0.log
?? src/main/webapp/RESOURCES/log/archived/error.2018-10-08.0.log
?? src/main/webapp/USER_DATA/211605292/
?? src/main/webapp/USER_POST_DATA/
?? src/main/webapp/USER_TEMP/2018/09/09/
?? src/main/webapp/USER_TEMP/2018/09/10/
?? src/main/webapp/USER_TEMP/2018/09/11/
?? src/main/webapp/USER_TEMP/2018/09/15/
?? src/main/webapp/USER_TEMP/2018/09/16/
?? src/main/webapp/USER_TEMP/2018/09/19/
?? src/main/webapp/USER_TEMP/2018/09/22/
!! .gradle/4.4/fileContent/
!! .gradle/4.4/fileHashes/resourceHashesCache.bin
```

**Comment by Alexander-Miller** [comment] 2018-11-03 17:39
> Ok, I have rechecked and I missed the space. Here is the correct format:

There is nothing wrong with what's saved. Let's try something else. First enable debug on error, then evaluate the following code, then evalute `(treemacs--restore)`. That ought to create the stack trace I need to understand this.

```
(defun treemacs--restore ()
  (when (file-exists-p treemacs-persist-file)
    (-let [str-list (--reject (or (string= it "")
                                  (s-starts-with? "#+STARTUP:" it))
                              (-> treemacs-persist-file (f-read) (s-lines)))]
      (if (and (>= (length str-list) 3)
               (--any? (s-matches? treemacs--persist-kv-regex it) str-list))
          (setq treemacs--workspaces (treemacs--read-workspaces (make-treemacs-iter :list str-list)))
        (-when-let (workspace (-> treemacs-persist-file (f-read 'utf-8) (read) (car)))
          (dolist (project (treemacs-workspace->projects workspace))
            (unless (-> project (treemacs-project->path) (f-exists?))
              (treemacs-log (format "Project at %s does not exist and was removed from the workspace."
                                    (propertize (treemacs-project->path project) 'face 'font-lock-string-face)))
              (setf (treemacs-workspace->projects workspace)
                    (delete project (treemacs-workspace->projects workspace)))))
          (setq treemacs--workspaces (list workspace)))))))
```
> When I run git status --porcelain --ignored from the project root dir, it got the following output:

Not seeing anything wrong either. Let's try something else. With debug on error try evaluating the following:

```
(-> "/home/test/edu" 
    (treemacs--git-status-process-function) 
    (treemacs--git-status-parse-function))
```

Also navigate to your project, find where treemacs is installed and run the git-status.py script in that directory like this:
`python ~/Documents/git/treemacs/src/scripts/treemacs-git-status.py /home/test/edu 5000 ""`

Finally and just to be sure, what's your python version?

**Comment by VisionaryAppDev** [comment] 2018-11-04 09:54
I could not find `treemacs--restore` inside M-x at all. So I don't know how to call it.

**Comment by Alexander-Miller** [comment] 2018-11-04 11:20
That is because that function is not interactive, you'll need to do things manually. Paste the code into the scratch buffer and use `eval-last-sexp`.

**Comment by VisionaryAppDev** [comment] 2018-11-04 14:44
Run `python ~/Documents/git/treemacs/src/scripts/treemacs-git-status.py /home/test/edu 5000 ""` I got: 
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
()
```

I am not sure what is going on but git is working properly here and the python that was installed here is `Python 3.7.1 (default, Oct 22 2018, 10:41:28)`.

And when calling `treemacs` and then I choose the dir and then pastes the whole function into the scratch buffer and position point at the end of the function bracket and calling `eval-last-sexp` and got this output back `treemacs--restore`

**Comment by Alexander-Miller** [comment] 2018-11-04 14:53
> fatal: not a git repository (or any parent up to mount point /)

You must run this script when you are *inside* /home/test/edu. It'll fire off a git status command based on the current working directory, so if you're anywhere else then that's where git will try to do its work. 

You do pass your project root to the script, but that's only for proper output printing. You really do have to be in the right place.

> Python 3.7.1 

That is an old enough version, so we've ruled that out as well.

>  calling eval-last-sexp and got this output back treemacs--restore

Pasting and evaluating the function means you have overwritten the one that's defined in treemacs. Originally this function does its work inside elisp's version of a try/catch. That prevents hard errors, but also hides the stack trace. That is why you need to overwrite that function.

After that is done you also need to call it to reproduce the error, so you also need to evaluate `(treemacs--restore)`.

**Comment by VisionaryAppDev** [comment] 2018-11-06 12:18
Ok for git I got the following output: 
```
~/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py ~/test/edu 5000 ""
/home/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py: line 1: from: command not found
/home/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py: line 2: from: command not found
/home/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py: line 3: from: command not found
/home/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py: line 4: from: command not found
/home/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py: line 5: import: command not found
/home/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py: line 7: syntax error near unexpected token `('
/home/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py: line 7: `GIT_ROOT  = str.encode(sys.argv[1])'						
```

And for the function you provide, first I evaluate the function definition and then I evaluate (treemacs--restore) and I got the following output:
```
Debugger entered--Lisp error: (void-variable treemacs-persist-file)
  (file-exists-p treemacs-persist-file)
  (if (file-exists-p treemacs-persist-file) (progn (let* ((str-list (let (result) (let ((list (s-lines (f-read treemacs-persist-file))) (it-index 0)) (while list (let ((it (car list))) (if (not (or (string= it "") (s-starts-with\? "#+STARTUP:" it))) (progn (setq result (cons it result))))) (setq it-index (1+ it-index)) (setq list (cdr list)))) (nreverse result)))) (if (and (>= (length str-list) 3) (---truthy\? (let (needle) (let ((list str-list) (continue t) (it-index 0)) (while (and list continue) (let ((it (car list))) (if (not (not needle)) (setq continue nil) (setq needle (s-matches\? treemacs--persist-kv-regex it)))) (setq it-index (1+ it-index)) (setq list (cdr list)))) needle))) (setq treemacs--workspaces (treemacs--read-workspaces (make-treemacs-iter :list str-list))) (let ((workspace (car (read (f-read treemacs-persist-file 'utf-8))))) (if workspace (progn (let ((--dolist-tail-- (treemacs-workspace->projects workspace)) project) (while --dolist-tail-- (setq project (car --dolist-tail--)) (if (f-exists\? (treemacs-project->path project)) nil (treemacs-log (format "Project at %s does not exist and was removed from the workspace." (propertize (treemacs-project->path project) 'face 'font-lock-string-face))) (let* ((v workspace)) (\(setf\ treemacs-workspace->projects\) (delete project (treemacs-workspace->projects workspace)) v))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (setq treemacs--workspaces (list workspace)))))))))
  treemacs--restore()
  eval((treemacs--restore) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp record nil)
  command-execute(eval-last-sexp record)
  helm-M-x(nil "eval-last-sexp")
  funcall-interactively(helm-M-x nil "eval-last-sexp")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

```

**Comment by Alexander-Miller** [comment] 2018-11-06 13:01
> ~/.emacs.d/elpa/treemacs-20181101.1650/treemacs-git-status.py ~/test/edu 5000 ""

You didn't run this as a python script.

> And for the function you provide, first I evaluate the function definition and then I evaluate (treemacs--restore) and I got the following output

Call treemacs first. The rest of it must be loaded as well.

**Comment by VisionaryAppDev** [comment] 2018-11-07 14:36
I have tried again and I got the following but I am not sure if it is the correct way:
```
(#s(treemacs-workspace "Default Workspace" (#s(treemacs-project "edu" "/home/test/edu"))))
```

**Comment by Alexander-Miller** [comment] 2018-11-07 16:45
> (#s(treemacs-workspace "Default Workspace" (#s(treemacs-project "edu" "/home/test/edu"))))

This part is correct. What you see is a workspace object that contains one project object. So loading your projects is working correctly now, it's the git part that does not, and the reason is this:

> D "src/main/webapp/USER_DATA/2018-09-02/1259550780.Screenshot from 2018-05-30 21-42-58.png"

The quotes in this line break my git parsing. Looks like there are special cases when git will output a quoted filename:

> If a filename contains whitespace or other nonprintable characters, that field will be quoted in the manner of a C string literal: surrounded by ASCII double quote (34) characters, and with interior special characters backslash-escaped.

I'm not seeing any such special characters, but it's a case I need to be aware of. Patch will drop soon.

Generally speaking git-mode does not support quotes in filenames. If you have them anyway it *will* break, and there's nothing I can do about it. You will have to either you`simple` git-mode, or no git-mode at all.

BTW: your treemacs config is out of date. You should use `deferred` instead of `extended` git-mode. The delay will make for a smoother experience, especially when there's so many git status lines to work through as in your case. You can call `treemacs-show-changelog` to read about recent changes.

**Comment by Alexander-Miller** [comment] 2018-11-08 05:58
Fix is a go, your issues should be fixed now.

**Closed** 2018-11-08 05:57 UTC
Labels: Bug

**Comment by VisionaryAppDev** [comment] 2018-11-08 17:10
> your treemacs config is out of date. You should use deferred instead of extended git-mode.

Actually, I copy all the configuration from the main github page and modify which property that I can understand. So is that you advice me to hange it to something like this? 

```
...
(`(t . t)
       (treemacs-git-mode 'extended))
      (`(t . _)
       (treemacs-git-mode 'simple))))
...


to 
...
(`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple))))
...
```

**Comment by eubarbosa** [comment] 2018-12-10 23:30
@Alexander-Miller 
hey same errror: [Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.

**Comment by Alexander-Miller** [comment] 2018-12-11 05:55
Is your treemacs up-to-date?

What does the content of the `treemacs-persist-file` look like *exactly*?
