### ISSUE TITLE
Projectile project renaming input field not being focused

### ISSUE THREAD

**Issue by programmador** [Alexander-Miller/treemacs#848] opened 2021-09-20 09:41 UTC
Renaming a projectile project via Treemacs works fine in console mode (emacs -nw).
Though doing the same in X11 causes quite weird interaction implications because the wrong field is getting input focus.
For example it may cause renaming of a project directory on disk instead of editing a project name.

See https://github.com/syl20bnr/spacemacs/issues/15040 for my original issue - it's a bit more detailed.

**Comment by Alexander-Miller** [comment] 2021-09-20 19:21
You can get the old behavior back with `treemacs-read-string-input`.

I would also like to debug this with you, if you don't mind. 

What's you setup like, do you use any kind of special Emacs like a special Mac version or a self-compiled Emacs 28?

What happens if you try `(cfrs-read "test")`? (cfrs uses posframe, so you can get rid of stuck popups with `posframe-delete-all`)

**Comment by programmador** [comment] 2021-09-21 07:22
Emacs 27.2, Spacemacs.
I didn't find neither `treemacs-read-string-input` nor `posframe-delete-all` with Helm.
Trying to evaluate it as lisp also fails.

`(cfrs-read "test")` behaves the same way as renaming a project: opens an unfocused popup.
Trying to type smth immediately causes weird things to happen.
In the most harmless case it would smth like "'a' is not defined".
Only after clicking it with a mouse I'm able to edit and see the result in elisp eval line.

**Comment by Alexander-Miller** [comment] 2021-10-06 18:11
> I didn't find neither treemacs-read-string-input

That's a variable, you should set it to `from-minibuffer` to enable the default behavior.

>  nor posframe-delete-all

That's an interactive command. `M-x` will find it, unless posframe, and thus cfrs, aren't loaded yet.

>  In the most harmless case it would smth like "'a' is not defined".

What's dos the stack trace look like when you enable `debug-on-error` before that happens?

Does it help if you us this version instead?

```Elisp
(defun cfrs-read (prompt &optional initial-input)
  "Read a string using a pos-frame with given PROMPT and INITIAL-INPUT."
  (if (not (or (display-graphic-p)
               (not (fboundp #'display-buffer-in-side-window))))
      (read-string prompt nil nil initial-input)
    (let* ((buffer (get-buffer-create " *Pos-Frame-Read*"))
           (border-color (face-attribute 'cfrs-border-color :background nil t))
           (cursor (cfrs--determine-cursor-type))
           (origin-frame (selected-frame))
           (frame (posframe-show
                   buffer
                   :min-height 1
                   :min-width (+ 40 (length prompt))
                   :internal-border-width 2
                   :internal-border-color border-color
                   :string ""
                   :override-parameters `(,@cfrs-frame-parameters
                                          (cursor-type . ,cursor)
                                          (no-accept-focus . nil)))))
      (with-selected-frame frame
        (x-focus-frame frame)
        (redirect-frame-focus origin-frame frame)
        (add-hook 'delete-frame-functions #'cfrs--on-frame-kill nil :local)
        (with-current-buffer buffer
          (cfrs-input-mode)
          (-each (overlays-in (point-min) (point-max)) #'delete-overlay)
          (erase-buffer)
          (-doto (make-overlay 1 2)
            (overlay-put
             'before-string
             (propertize (concat " " prompt) 'face 'minibuffer-prompt))
            (overlay-put 'rear-nonsticky t)
            (overlay-put 'read-only t))
          (when initial-input
            (insert initial-input))
          (when (and (bound-and-true-p evil-mode)
                     (fboundp 'evil-insert-state))
            (evil-insert-state nil))
          (end-of-line)
          (recursive-edit)
          (cfrs--hide)
          (s-trim (buffer-string)))))))
```

**Comment by programmador** [comment] 2021-10-10 16:43
I've tried to define the function in IELM and run. Nothing changed. The field appears unfocused.
And also I've gound debug-on-error toggling capability via HELM and switched it on though I don't know whether it affects IELM.
Anyway I didn't see any kind of errors or stacktraces.

**Comment by programmador** [comment] 2021-10-11 09:18
And no matter whether it is vanilla emacs 27.2 or spacemacs - I tried both with same result.

**Comment by Alexander-Miller** [comment] 2021-10-11 16:05
What about either of these?

```Elisp
(select-frame
 (window-frame
  (display-buffer-in-child-frame
   (current-buffer)
   '((child-frame-parameters . '((width . 100)
                                 (height . 10)
                                 (no-accept-focus . nil)))))))
```

```Elisp
(select-frame-set-input-focus
 (window-frame
  (display-buffer-in-child-frame
   (current-buffer)
   '((child-frame-parameters . '((width . 100)
                                 (height . 10)
                                 (no-accept-focus . nil)))))))
```

If neither one works we'll have to take things up with emacs-devel.

**Comment by programmador** [comment] 2021-10-11 17:27
The first one, `select-frame` is successful: popup is created focused.
The second one `select-frame-set-input-focus` is not.

As before, I've also tested with keeping mouse cursor inside or outside of place for the popup. It does not affect anything.

**Comment by programmador** [comment] 2021-10-14 10:37
Hmm, installed version of cfrs is now `20211013.1802`.
And it really has the next section in source:
```
      (with-selected-frame frame
        (select-frame frame)
        (x-focus-frame frame)
```
But there's no difference, renaming input field still appears unfocused.
I tried changing it back to `select-frame-set-input-focus`  - there's no difference.

**Comment by Alexander-Miller** [comment] 2021-10-19 19:47
Same game as before then, but this time using posframe. Does anyone of there work?

```Elisp
(x-focus-frame
 (posframe-show
  (current-buffer)
  :height 5 :width 20
  :override-parameters '((no-accept-focus . nil))))

(select-frame
 (posframe-show
  (current-buffer)
  :height 5 :width 20
  :override-parameters '((no-accept-focus . nil))))

(select-frame-set-input-focus
 (posframe-show
  (current-buffer)
  :height 5 :width 20
  :override-parameters '((no-accept-focus . nil))))
```

**Comment by programmador** [comment] 2021-12-10 15:43
I have to tell You that recently I had to use another PC with almost same setup excluding the fact that it has xorg instead of wayland. And I've accidently noticed that everything is working fine. It seems like after Your fix You've uploaded some time ago.

Remember You asked me which of `select-frame` or `select-frame-input-focus` works and I've told that the first one. At that time You told me that for You the second one is working. So for me on another PC with xorg also the second one works, not the first one.

As for the latest 3 examples with postframe - I couldn't test it as I probably should as I didn't see anything looking like a frame though the scrolling became somewhat strange after calling some of the functions. Probably the frame is opening with a zero-width border and it makes hard to tell whether it's working as expected.

Anyway it seems like everything is more than okay with cfrs currently. The problem is much more lowlevel. It is related not to elisp code but rather to GTK which emacs runs in. Or maybe even a layer lower: in xorg-wayland implementation. Or maybe in wlroots which is my desktop environment (sway/wayland) is built upon. Sounds like "anywhere" :-)
I'd be grateful if You advice me more proper place for a report of a bug of this kind.

**Comment by Alexander-Miller** [comment] 2021-12-13 18:03
The next step further up the chain would be posframe, if its frames are unselectable for you.

You can also try the last experiment again with a few extra parameters to make sure the child frame is visible:

```Elisp
(x-focus-frame
 (posframe-show
  (current-buffer)
  :height 5 :width 20
  :border-color "red"
  :border-width 3
  :override-parameters '((no-accept-focus . nil))))
```

**Comment by programmador** [comment] 2021-12-14 11:38
Wow, red border does the trick. So, in wayland:
* x-focus-frame - focus disabled
* select-frame - focus enabled
* select-frame-set-input-focus - focus enabled
Of course I'll test the same under Xorg a bit later to compare results.

**Comment by programmador** [comment] 2021-12-17 09:15
Xorg:
x-focus-frame - focus enabled
select-frame - focus disabled
select-frame-set-input-focus - focus enabled

So... The difference between wayland and xorg is in x-focus-frame behaviour, Two others are identical.

**Comment by programmador** [comment] 2021-12-17 09:18
Oh, no. Two first deffer, third is identical.
Here's focus table:
| | Wayland | Xorg |
| --- | --- | --- |
| x-focus-frame | - | + |
| select-frame | + | - |
| select-frame-set-input-focus | + | + |

**Comment by Alexander-Miller** [comment] 2021-12-23 13:24
> select-frame-set-input-focus

The table says it works in both environments, but haven't we tried using that in cfrs already?

**Comment by programmador** [comment] 2021-12-23 14:11
As for these two variants:
https://github.com/Alexander-Miller/treemacs/issues/848#issuecomment-940159861

I've rechecked under wayland. Currently both of them do work.
Both in Spacemacs and vanilla Emacs.
Maybe smth was updated - either emacs or some wayland libs.

Anyway project renaming dialog is still unfocused.

From cfrs-20211013.1802:
```
      (with-selected-frame frame
        (select-frame frame)
        (x-focus-frame frame)
```

I tried to change select-frame to select-frame-set-input-focus. It has no effect.

Also I've rechecked this in wayland:
```

(select-frame-set-input-focus
 (posframe-show
  (current-buffer)
  :height 5 :width 20
  :border-color "red"
  :border-width 3
  :override-parameters '((no-accept-focus . nil))))
```

Actually I can't understand what's going on. It looks like both parent and child buffers are focused. Whe I'm typing - text appeaars in both buffers simultaneously.

**Comment by Alexander-Miller** [comment] 2021-12-23 15:12
>  It looks like both parent and child buffers are focused. Whe I'm typing - text appeaars in both buffers simultaneously.

Try this combination:

```Elisp
(select-frame-set-input-focus frame)
(redirect-frame-focus (frame-parent frame) frame)
```

**Comment by Alexander-Miller** [comment] 2021-12-23 15:24
And grab the latest cfrs and posframe - I've updated to use posframe's accept-focus argument instead of overriding it.

**Comment by programmador** [comment] 2021-12-24 15:38
Cfrs version is still the same (according to folder name): `cfrs-20211013.1802`.
Though I've updated via `configuration-layer/packages` and also tried clearing `elpa` dir and restarting spacemacs to make it reinstall everything from scratch. Probably the specific version is configured somewhere in spacemacs though previously as I remember the update was performed immediately and successfully.
Posframe is `posframe-20211222.256` - is it ok?

Sorry, I'm skilled in dozen of languages including functional but neither of them is LISP or it's dialects. So as for the combination - I didn't understand what to do. If I need to have `frame` variable - seems like I have to modify cfrs source. I tried these variants:

```
      (with-selected-frame frame
        (select-frame-set-input-focus frame)
        (redirect-frame-focus (frame-parent frame) frame)
        (add-hook 'delete-frame-functions #'cfrs--on-frame-kill nil :local)
        (with-current-buffer buffer

```

```
      (with-selected-frame frame
        (select-frame frame)
        (x-focus-frame frame)
        (select-frame-set-input-focus frame)
        (redirect-frame-focus (frame-parent frame) frame)
        (add-hook 'delete-frame-functions #'cfrs--on-frame-kill nil :local)
        (with-current-buffer buffer
```

Nothing helped.

**Comment by wildwestrom** [comment] 2022-01-04 04:08
Just popping in here to say it doesn't work on wayland (wlroots/sway) either.
When I type `R` to rename, on emacs 27 and 28, I'm unable to do anything within emacs and I'm forced to close it. The pop-up window just stays and won't close.

On emacs 29, I can at least focus on the window and then type in my change, then hit enter and see the change complete. The problem is that then I'm not allowed to enter emacs and yet again I'm forced to quit emacs from outside.

**Comment by Alexander-Miller** [comment] 2022-10-05 20:23
Let's try something else then. The child frame is only an option, we can turn it off. Can Emacs detect when it's running under wayland? What does `(window-system)` return on your end?

**Comment by wildwestrom** [comment] 2022-10-05 20:28
@Alexander-Miller 
```emacs-lisp
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (window-system)
pgtk
```

**Comment by programmador** [comment] 2022-10-26 10:23
emacs 28.2 from Arch vanilla repo.
The answer is `x`

**Comment by Alexander-Miller** [comment] 2022-10-26 20:00
>  The answer is x

Is this correct, did you test it on an X setup, or are you actually running wayland? If it's Emacs that's in the wrong what's the output of `echo $XDG_SESSION_TYPE`?

**Comment by programmador** [comment] 2022-10-27 16:23
I've tried [emacs-gcc-wayland-devel-bin](https://aur.archlinux.org/packages/emacs-gcc-wayland-devel-bin)
(vanilla emacs operates via xwayland)
Emacs version is actually the same as for vanilla `emacs` package from arch repository.
So, here are results:
* It shows lots of warnings.
* It always consumes 100% of one CPU.
* It tells `pygtk` instead of `x`
* `xeyes` does not see mouse on top of it.
* Renaming bugs in Treemacs are the same: an additional mouse click is required to focus editable field after editing is started.

**Comment by Alexander-Miller** [comment] 2022-10-31 13:47
Do different values for `focus-follows-mouse` and `mouse-autoselect-window` change anything?

**Comment by Alexander-Miller** [comment] 2022-10-31 13:58
Let's also see if simulating a mouse click works. Change your cfrs code like this:
```Diff
       (with-selected-frame frame
         (select-frame frame)
         (x-focus-frame frame)
+        (let ((pos (posn-at-point)))
+          (message "Simulate click at %s" pos)
+          (setf unread-command-events (cons (list 'mouse-1 pos) unread-command-events)))
         (add-hook 'delete-frame-functions #'cfrs--on-frame-kill nil :local)
         (with-current-buffer buffer
           (cfrs-input-mode)
```

Depending on where your Emacs believes your point is we might have to explicitly say where the click is. If it works correctly the log will look like this:

`Simulate click at (#<window 593 on  *Pos-Frame-Read*> 1 (0 . 0) 0 ( New name:  . 0) 1 (0 . 0) nil (0 . 0) (0 . 0))`

**Comment by programmador** [comment] 2022-11-04 15:04
No, nothing happens.
For example "messages" buffer has "Mark set" printed when I double-click the file name after pressing "R".
When I press "R" and then single-click to set focus and rename a file as usually - nothing is printed.

**Comment by Alexander-Miller** [comment] 2022-11-07 20:37
> No, nothing happens.

Can't be. The added lines are not an optional path, that code *must* run. Either you missed calling `eval-buffer` or you restarted Emacs and it used the old byte code.

**Comment by programmador** [comment] 2022-11-09 14:13
1. I've added the code:
![screenshot_2022-11-09-160805](https://user-images.githubusercontent.com/674995/200852524-5812bdbc-feaa-45f9-a366-4ce7ae89419d.png)
2. Started emacs from scratch and performed next steps:
![screenshot_2022-11-09-160733](https://user-images.githubusercontent.com/674995/200852641-124934a3-411d-40d8-8f8d-f1733f59c47b.png)

**Comment by programmador** [comment] 2022-11-20 15:26
Sorry, I had multiple folders/versions in `~/.emacs.d/melpa` and was editing cfrs in the wrong elpa. Stupid mistake.
So here's an output (renaming twice):
```
Simulate click at (#<window 14 on  *Pos-Frame-Read*> 1 (0 . 0) 0 nil 1 (0 . 0) nil (0 . 0) (0 . 0))
[Treemacs] Renamed project ruler to rulers.
Simulate click at (#<window 14 on  *Pos-Frame-Read*> 1 (0 . 0) 0 ( New name:  . 0) 1 (0 . 0) nil (0 . 0) (0 . 0))
[Treemacs] Renamed project rulers to ruler.
```

Nothing more happens. If I understood right it's okay.

**Comment by Alexander-Miller** [comment] 2022-11-23 15:05
The click looks like it's where it's supposed to be. But it doesn't help, right?

Let's exclude your config, if that doesn't help I'll set up a minimal example for a bug report at emacs-devel. 

Clone the treemacs repo and run the command `make clean-start`. That will start a blank Emacs instance with nothing loaded except for treemacs' dependencies. You will need make and cask for this to work. 

Then you'll need to run these 2 lines because the clean start doesn't handle autoloads:

```Elisp
(require 'treemacs-file-management)
(require 'cfrs)
```

At least that's the easiest way to run treemacs from `emacs -q`. The other option is *a lot* of manual loading.

Then start treemacs and try to rename something. 

If focus still doesn't work we'll go to emacs-devel (or whoever is responsible for your version of Emacs). If it does then we'll have a config to bisect.

**Comment by iamkarlson** [comment] 2023-05-28 13:09
This issue isn't stale. However, I see that there's a lot investigation still going on. I'm using doomemacs, and this issue occurs on 2 different machines with wayland. If I understood correctly, some manual verification is needed to rule out an emacs bug, right? What would be a minimal example of doing so?

**Comment by iamkarlson** [comment] 2023-05-28 14:05
I found a workaround tho: when you click and hold mouse clicked over this field, it's kinda "focused" so I can hit RET to close the window.

**Comment by Alexander-Miller** [comment] 2023-05-29 20:48
> What would be a minimal example of doing so?

As a first step you can try 

```Elisp
(select-window
 (display-buffer-in-child-frame
  (current-buffer)
  nil))
```

However I would prefer not to use child frames at all if I can be confidently detect wayland being used. To that end can you tell me what your `XDG_SESSION_TYPE`, `DISPLAY` and `WAYLAND_DISPLAY` environment variables look like?

**Comment by iamkarlson** [comment] 2023-05-31 10:27
Here you go:
```
❯ echo "XDG_SESSION:$XDG_SESSION DISPLAY:$DISPLAY WAYLAND_DISPLAY:$WAYLAND_DISPLAY" 
XDG_SESSION: DISPLAY::1 WAYLAND_DISPLAY:wayland-1
```

**Closed** 2023-07-01 10:18 UTC
Labels: Bug, UI

**Comment by Alexander-Miller** [comment] 2023-07-01 10:19
All right, without other solution in sight I've now set treemacs to use the minibuffer if it detects you are using wayland (by looking at the `WAYLAND_DISPLAY` variable).

**Comment by iamkarlson** [comment] 2023-07-02 12:51
Have you made it default?

**Comment by Alexander-Miller** [comment] 2023-07-02 13:22
I changed the default based on whether you have wayland.

```Elisp
(defcustom treemacs-read-string-input
  (if (getenv "WAYLAND_DISPLAY") 'from-minibuffer 'from-child-frame)
  ...)
```
