### ISSUE TITLE
treemacs file icon disappears

### ISSUE THREAD

**Issue by sound2gd** [Alexander-Miller/treemacs#66] opened 2017-09-28 08:00 UTC
I come from spacemacs and after this config I , file icon missing

```emacs-lisp
(defconst treemacs-packages
  '(treemacs
    treemacs-evil
    treemacs-projectile))

(defun treemacs/init-treemacs-evil ()
  (use-package treemacs-evil 
   :ensure t
   :demand t))

(defun treemacs/init-treemacs ()
  (use-package treemacs
    :ensure t
    :defer t
    ;; :config
    :bind
    (:map global-map
          ([f3]        . treemacs-toggle)
          ("M-0"       . treemacs-select-window)
          ("C-c 1"     . treemacs-delete-other-windows)
          ("M-m ft"    . treemacs-toggle)
          ("M-m fT"    . treemacs)
          ("M-m f C-t" . treemacs-find-file))))

(defun treemacs/init-treemacs-projectile ()
  (use-package treemacs-projectile
    :defer t
    :ensure t
    :config
    (setq treemacs-header-function #'treemacs-projectile-create-header)
    :bind (:map global-map
                ("M-m fP" . treemacs-projectile)
                ("M-m fp" . treemacs-projectile-toggle))))

(spacemacs|use-package-add-hook treemacs
  :post-config
  (progn
    (setq treemacs-follow-after-init          t
          treemacs-width                      35
          treemacs-indentation                2
          treemacs-git-integration            t
          treemacs-collapse-dirs              3
          treemacs-silent-refresh             nil
          treemacs-change-root-without-asking nil
          treemacs-sorting                    'alphabetic-desc
          treemacs-show-hidden-files          t
          treemacs-never-persist              nil
          treemacs-is-never-other-window      nil
          treemacs-goto-tag-strategy          'refetch-index)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)))
;;; packages.el ends here

```

and this is the effect

![image](https://user-images.githubusercontent.com/10735388/30955417-262aeb84-a466-11e7-90df-951aaf546e81.png)

**Comment by Alexander-Miller** [comment] 2017-09-28 17:27
Well that's new. First the usual: update all treemacs packages (the value of `treemacs-version` should be 1.11.2) and restart emacs. If the icons still dont appear tell me

 * do you see any error output relating to treemacs in the messages buffer?
 * what's the value of `treemacs-no-images`?
 * what's the value of `treemacs-icon-css`?
 * what happens if you run `(insert treemacs-icon-css)`?
 * can your emacs display images? What happens if you try to open any image file in emacs?

**Comment by sound2gd** [comment] 2017-09-29 04:02
treemacs version is 1.11.1
- treemacs-no-images:nil
- treemacs-icon-css:#("  " 0 1 (display (image :type png :file "/Users/cris/.emacs.d/elpa/treemacs-20170927.1226/icons/css.png" :scale 1 :ascent center :background unspecified) img-selected (image :type png :file "/Users/cris/.emacs.d/elpa/treemacs-20170927.1226/icons/css.png" :scale 1 :ascent center :background unspecified) img-unselected (image :type png :file "/Users/cris/.emacs.d/elpa/treemacs-20170927.1226/icons/css.png" :scale 1 :ascent center :background unspecified)))
- my emacs can display images

**Comment by Alexander-Miller** [comment] 2017-09-29 05:55
What about trying to insert the icon? That's the important bit, it's exactly what treemacs does to display its icons.

**Comment by sound2gd** [comment] 2017-09-29 07:24
when inserting icon ,it shows treemacs buffer is read only....

**Comment by sound2gd** [comment] 2017-09-29 07:31
after eval `(setq inhibit-read-only t)` I can execute `(insert treemacs-icon-css)`,
but it is still no icons

![image](https://user-images.githubusercontent.com/10735388/31005454-4d5c1e6a-a52b-11e7-9423-f9cb95a16936.png)

**Comment by Alexander-Miller** [comment] 2017-09-29 07:50
> after eval (setq inhibit-read-only t) I can execute (insert treemacs-icon-css)

I didn't mean you should try and run this in the treemacs. In fact we already know it doesn't work there. Try it somewhere else, like the scratch buffer. The image looks built correctly so you should see the icon when you insert it.

**Comment by sound2gd** [comment] 2017-09-29 13:45
in scratch buffer I also get nothing.
here it is 
![image](https://user-images.githubusercontent.com/10735388/31018667-7ad230bc-a55f-11e7-85f2-35ae340d47a0.png)

**Comment by Alexander-Miller** [comment] 2017-09-29 15:00
All right, now we know that treemacs is correctly loading and creating its images, but they cannot be displayed. Now we need to find out if this is specific to treemacs, or affects all images created in elisp.

Grab the path of some random png image file on your system, unrelated to treemacs, and run the following code:

```
(progn
  (defvar debug-image (create-image "/path/to/image.png" 'png nil :ascent 'center))
  (insert "\nInserting created image directly: ")
  (insert-image debug-image)
  (defvar debug-image-string (propertize " " 'display debug-image))
  (insert "\nInsert created image string: " debug-image-string))
```
For me the output looks like this: https://i.imgur.com/FoKtN1A.png

**Comment by sound2gd** [comment] 2017-09-30 01:18
after running the code
![image](https://user-images.githubusercontent.com/10735388/31040945-44d67e12-a5c0-11e7-88c6-330112c78adf.png)

**Comment by Alexander-Miller** [comment] 2017-09-30 13:44
So creating images works. That means there's probably something off about the specific way that treemacs handles its images. I do a bit of interference with image backgrounds to keep things looking nice with hl-line-mode, let's see what that looks like on your end. What's the output of the following code (it must be run after treemacs has loaded):
```
(let ((icon-selected) (icon-unselected) (test-icon) (icon-display) (icon-full))
  (insert "\nSelected icon background: " treemacs--selected-icon-background)
  (insert "\nUnselected icon background: " treemacs--not-selected-icon-background)
  (setq icon-selected (create-image  "~/Documents/git/treemacs/icons/css.png" 'png nil :ascent 'center))
  (insert "\nSelected icon version: ")
  (insert-image icon-selected)
  (setq icon-unselected (create-image "~/Documents/git/treemacs/icons/css.png" 'png nil :ascent 'center))
  (insert "\nUnselected icon version: ")
  (insert-image icon-unselected)
  (treemacs--set-img-property icon-selected   :background treemacs--selected-icon-background)
  (treemacs--set-img-property icon-unselected :background treemacs--not-selected-icon-background)
  (insert "\nSelected icon with background: ")
  (insert-image icon-selected)
  (setq icon-unselected (create-image "~/Documents/git/treemacs/icons/css.png" 'png nil :ascent 'center))
  (insert "\nUnselected icon with background: ")
  (insert-image icon-unselected)
  (setq icon-display (concat (propertize " " 'display icon-unselected) " "))
  (setq icon-full (concat (propertize " " 'display icon-unselected
                                      'img-selected icon-selected
                                      'img-unselected icon-unselected)
                          " "))
  (insert "\nIcon with only display property: " icon-display)
  (insert "\nIcon with all properties: " icon-full))
```

Another thing to try is make sure the problem is some part of your configuration. To test this delete treemacs, start emacs with `emacs -q`, and run the following code:
```
(mapcar (lambda (d) (when (file-directory-p d) (add-to-list 'load-path d))) (directory-files "~/.emacs.d/elpa" t))
(require 'use-package)
(use-package treemacs :ensure t :demand t)
```

and manually call `treemacs`. Are the icons still gone?

**Comment by kinleyd** [comment] 2017-10-02 09:57
Chiming in to say I have the same problem, with a slight variation:

Icons show up when I install treemacs and lasts for the session. However, if I reboot, the icons don't reappear. Reinstalling gets it back but again, only for the session.

On one occasion the highlighted folder/file only had the icon visible.

**Comment by Alexander-Miller** [comment] 2017-10-02 18:24
The more parts of this puzzle I see the weirder it gets.  Let's look into this then:

 * What's the code block from my previous comment output for you, both when treemacs' icons are there and when they are not (with file paths adjusted for you installation)?

 * What's the value of `treemacs-no-images`, `treemacs-dir` and `treemacs-icon-css`, again both when icons are there and when they are not?

 * Are the icons even physically on our hard drive the second time around? 

 * Does it make any difference if you go to `treemacs--update-icon-selection` in treemacs-visuals.el and just comment out the function body and recompile the file with `emacs-lisp-byte-compile`?

**Comment by kinleyd** [comment] 2017-10-03 05:46
@Alexander-Miller, thanks for treemacs.

Here's what I have so far:

Apart from the absence of the icons, no error messages are reported in messages buffer.

1.    What's the code block from my previous comment output for you, both when treemacs' icons are there and when they are not (with file paths adjusted for you installation)?

`(progn
  (defvar debug-image (create-image "/path/to/image.png" 'png nil :ascent 'center))
  (insert "\nInserting created image directly: ")
  (insert-image debug-image)
  (defvar debug-image-string (propertize " " 'display debug-image))
  (insert "\nInsert created image string: " debug-image-string)) `

This works, and the png is opened in the scratch buffer.
`(let ((icon-selected) (icon-unselected) (test-icon) (icon-display) (icon-full))
  (insert "\nSelected icon background: " treemacs--selected-icon-background)
  (insert "\nUnselected icon background: " treemacs--not-selected-icon-background)
  (setq icon-selected (create-image  "~/Documents/git/treemacs/icons/css.png" 'png nil :ascent 'center))
  (insert "\nSelected icon version: ")
  (insert-image icon-selected)
  (setq icon-unselected (create-image "~/Documents/git/treemacs/icons/css.png" 'png nil :ascent 'center))
  (insert "\nUnselected icon version: ")
  (insert-image icon-unselected)
  (treemacs--set-img-property icon-selected   :background treemacs--selected-icon-background)
  (treemacs--set-img-property icon-unselected :background treemacs--not-selected-icon-background)
  (insert "\nSelected icon with background: ")
  (insert-image icon-selected)
  (setq icon-unselected (create-image "~/Documents/git/treemacs/icons/css.png" 'png nil :ascent 'center))
  (insert "\nUnselected icon with background: ")
  (insert-image icon-unselected)
  (setq icon-display (concat (propertize " " 'display icon-unselected) " "))
  (setq icon-full (concat (propertize " " 'display icon-unselected
                                      'img-selected icon-selected
                                      'img-unselected icon-unselected)
                          " "))
  (insert "\nIcon with only display property: " icon-display)
  (insert "\nIcon with all properties: " icon-full))`

helm-M-x: Wrong type argument: char-or-string-p, unspecified

2.    What's the value of treemacs-no-images, treemacs-dir and treemacs-icon-css, again both when icons are there and when they are not?

helm-M-x: Symbol’s function definition is void: treemacs-no-images
helm-M-x: Symbol’s function definition is void: treemacs-icon-css
helm-M-x: Symbol’s function definition is void: treemacs-dir

3.    Are the icons even physically on our hard drive the second time around?

Yes, they are there.

4.    Does it make any difference if you go to treemacs--update-icon-selection in treemacs-visuals.el and just comment out the function body and recompile the file with emacs-lisp-byte-compile?

No. Nothing changed.

**Comment by Alexander-Miller** [comment] 2017-10-03 10:23
> The above returns this error when in a session which icons are not visible:
helm-M-x: Wrong type argument: char-or-string-p, unspecified

I assume you ran `eval-buffer` from helm? Otherwise that error makes no sense. Please try again after running `toggle-debug-on-error`. That should give us a nice stack trace.
Also do update treemacs. I've just pushed my tags, there will be a new version with the next melpa build.

> helm-M-x: Symbol’s value as variable is void: treemacs-no-images

That was introduced after 1.11.1 for non-graphical environments. If you're in a GUI its value should be nil.

> I'm not too familiar with elisp and used message to return values for these properties/variables. Please let me know if that is correct.

Messages will give you the string representation of objects. That's good enough if you want to know if something is nil, but for my icon I need the value of its text properties - basically meta data that's attached to the string. Strangely enough neither of your outputs is as expected. If the icon is defined the message should look like this:
`#("  " 0 1 (display (image :type png :file
  "/home/a/Documents/git/treemacs/icons/css.png" :scale 1 :ascent center
  :background "#2d2d31") img-selected (image :type png :file
  "/home/a/Documents/git/treemacs/icons/css.png" :scale 1 :ascent center
  :background "#383844") img-unselected (image :type png :file
  "/home/a/Documents/git/treemacs/icons/css.png" :scale 1 :ascent center
  :background "#2d2d31")))`

Of course not seeing anything is the interesting part. Something is off during icon creation and that should absolutely not happen. The big code block above emulates that process. If I get a good stack trace there I might have a clue to what's going on. Also do check the icon's value again for this case using `describe-variable`.

> No. Nothing changed.

When icons do appear there should now be a gap in the hl-line-mode highlight in treemacs around the icon. I need to manually adjust the icons' background color to make it match, that's what all these text properties in my icons are for.

**Comment by kinleyd** [comment] 2017-10-03 11:21
> I assume you ran eval-buffer from helm? Otherwise that error makes no sense. 
Yes.

> Please try again after running toggle-debug-on-error. That should give us a nice stack trace.
Toggled.

> Also do update treemacs. I've just pushed my tags, there will be a new version with the next melpa build.
Thanks, been waiting on that. Updated to v. 1.11.3 now.

> The big code block above emulates that process. If I get a good stack trace there I might have a clue to what's going on.

In an icon-less session:
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p unspecified)
  insert("\nSelected icon background: " unspecified)
  (let ((icon-selected) (icon-unselected) (test-icon) (icon-display) (icon-full)) (insert "\nSelected icon background: " treemacs--selected-icon-background) (insert "\nUnselected icon background: " treemacs--not-selected-icon-background) (setq icon-selected (create-image "~/.emacs.d/elpa/treemacs-1.11.3/icons/css.png" (quote png) nil :ascent (quote center))) (insert "\nSelected icon version: ") (insert-image icon-selected) (setq icon-unselected (create-image "~/.emacs.d/elpa/treemacs-1.11.3/icons/css.png" (quote png) nil :ascent (quote center))) (insert "\nUnselected icon version: ") (insert-image icon-unselected) (treemacs--set-img-property icon-selected :background treemacs--selected-icon-background) (treemacs--set-img-property icon-unselected :background treemacs--not-selected-icon-background) (insert "\nSelected icon with background: ") (insert-image icon-selected) (setq icon-unselected (create-image "~/.emacs.d/elpa/treemacs-1.11.3/icons/css.png" (quote png) nil :ascent (quote center))) (insert "\nUnselected icon with background: ") (insert-image icon-unselected) (setq icon-display (concat (propertize " " (quote display) icon-unselected) " ")) (setq icon-full (concat (propertize " " (quote display) icon-unselected (quote img-selected) icon-selected (quote img-unselected) icon-unselected) " ")) (insert "\nIcon with only display property: " icon-display) (insert "\nIcon with all properties: " icon-full))
  eval-region(17076 18434)  ; Reading at buffer position 18461
  funcall-interactively(eval-region 17076 18434)
  #<subr call-interactively>(eval-region record nil)
  apply(#<subr call-interactively> eval-region (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> eval-region record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (eval-region record nil))
  call-interactively(eval-region record nil)
  command-execute(eval-region record)
  helm-M-x(nil #("eval-region" 0 11 (match-part "eval-region")))
  funcall-interactively(helm-M-x nil #("eval-region" 0 11 (match-part "eval-region")))
  #<subr call-interactively>(helm-M-x nil nil)
  apply(#<subr call-interactively> helm-M-x (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> helm-M-x nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (helm-M-x nil nil))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)


> Also do check the icon's value again for this case using describe-variable.

(describe-variable 'treemacs-no-images) =>
treemacs-no-images is a variable defined in ‘treemacs-customization.el’.
Its value is nil

(describe-variable 'treemacs-icon-css) => 
treemacs-icon-css is a variable defined in ‘treemacs-mode.el’.
Its value is
#("  " 0 1
  (display
   (image :type png :file "/home/../.emacs.d/elpa/treemacs-1.11.3/icons/css.png" :ascent center :background unspecified)
   img-selected
   (image :type png :file "/home/../.emacs.d/elpa/treemacs-1.11.3/icons/css.png" :ascent center :background unspecified)
   img-unselected
   (image :type png :file "/home/../.emacs.d/elpa/treemacs-1.11.3/icons/css.png" :ascent center :background unspecified)))

(describe-variable 'treemacs-dir) =>
treemacs-dir is a variable defined in ‘treemacs-impl.el’.
Its value is "/home/kdd/.emacs.d/elpa/treemacs-1.11.3/"

**Comment by Alexander-Miller** [comment] 2017-10-03 12:09
> :background unspecified

Well damn. I really should've paid better attention, this already came up with the very first answer.

You see treemacs tries to be smart and get the colors it needs for the hl-line-mode recoloring from your theme. Looks like it's not working for you for whatever reason.
Look up the value of `treemacs--selected-icon-background`. It should say unspecified. Also what do the following pieces of code output:

 * `(face-attribute 'hl-line :background nil t)`
 * `(face-attribute 'default :background nil t)`

The output should be a hex color in both cases. Or unspecified, which means youre using a strange theme.

Try using a different theme, maybe one of the defaults, like adwaita. The icons should display correctly then. If this does work I need to know which theme youre using so I can properly look into it.

**Comment by kinleyd** [comment] 2017-10-03 12:30
> Look up the value of treemacs--selected-icon-background. It should say unspecified. 
treemacs--selected-icon-background is a variable defined in ‘treemacs-visuals.el’.
Its value is ‘unspecified’

> Also what do the following pieces of code output:
(message (face-attribute 'hl-line :background nil t)) => darkolivegreen
(message (face-attribute 'default :background nil t)) => gray8

> The output should be a hex color in both cases. Or unspecified, which means youre using a strange theme. Try using a different theme, maybe one of the defaults, like adwaita. The icons should display correctly then. If this does work I need to know which theme youre using so I can properly look into it.

I am using a custom theme. Will try some standard theme and get back to you.

**Comment by kinleyd** [comment] 2017-10-03 12:47
I tried a number of themes - adwaita, deeper blue, wombat and tango.
In all cases, only the icon for the currently selected file/folder is visible. Interesting, once I switched themes  and returned to my custom theme, I had the same behaviour.

**Comment by Alexander-Miller** [comment] 2017-10-03 12:52
Strange. What about just starting emacs, then treemacs and then loading a new theme? What are the values of `treemacs--selected-icon-background` and `treemacs--not-selected-icon-background` then?

**Comment by Alexander-Miller** [comment] 2017-10-03 13:00
> Looking at the alignment, I wonder if it has anything to do indentation?

Unlikely. It just looks off since the icons are much larger than your font.

Let's try another thing. So far it's fairly clear that the issue relates to the way treemacs is being loaded, so let's make sure treemacs is not loaded alongside emacs (you should always do this anyway to improve your startup time). To achieve this just pack everything treemacs-related, except the keybinds, into an eval-after-load block, like this:

```
(with-eval-after-load 'treemacs
    (config goes here))
```

Using the use-package snippet from the read will have the same effect.

**Comment by kinleyd** [comment] 2017-10-03 13:22
I used the use-package snippet from readme. I had to remove references to M-m, etc. as it triggered errors - is that a spacemac thing?

Upon rebooting, I get these in the message buffer (I did run th off hydra once):

Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  button-start(nil)
  treemacs--create-branch("/home/.." 0 #<process Process Future> #<process Process Future<1>>)
  treemacs--build-tree("/home/..")
  treemacs-refresh()
  treemacs-toggle-show-dotfiles()
  funcall-interactively(treemacs-toggle-show-dotfiles)
  #<subr call-interactively>(treemacs-toggle-show-dotfiles)
  apply(#<subr call-interactively> treemacs-toggle-show-dotfiles nil)
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> treemacs-toggle-show-dotfiles)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> treemacs-toggle-show-dotfiles)
  call-interactively(treemacs-toggle-show-dotfiles)
  hydra--call-interactively-remap-maybe(treemacs-toggle-show-dotfiles)
  treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit()
  funcall-interactively(treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit)
  #<subr call-interactively>(treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit nil nil)
  apply(#<subr call-interactively> treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit nil nil))
  call-interactively(treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit nil nil)
  command-execute(treemacs--helpful-hydra/treemacs-toggle-show-dotfiles-and-exit)

**Comment by Alexander-Miller** [comment] 2017-10-03 13:59
> I used the use-package snippet from readme. I had to remove references to M-m, etc. as it triggered errors - is that a spacemac thing?

In your screenshot it looked like all the declarations were top-level. M-m is just the leader key in spacemacs if you dont use evil-mode. Its just  a normal keybind and should not cause any issues. Whats the error it causes for you?

> Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)

That one is unrelated to the icons issue. It's an edge case in the directory collapse script. I'm working on a fix now, in the meantime you can get around it by either setting `treemacs-collapse-dirs` to zero or not setting dotfiles to hidden.

**Comment by seagle0128** [comment] 2017-10-03 14:21
I encountered the same issue some times. It recovered after refreshing.

**Comment by kinleyd** [comment] 2017-10-03 14:24
("M-m ft"    . treemacs-toggle) gives me:
Invalid function: "M-m ft"

> you can get around it by either setting treemacs-collapse-dirs to zero or not setting dotfiles to hidden
Will do that.

I forgot to mention that the icons are still missing despite using the use-package configuration for treemacs.

**Comment by Alexander-Miller** [comment] 2017-10-03 14:51
> ("M-m ft" . treemacs-toggle)

This specific syntax is meant only for use-package's `:bind` section. In your own config you'd do something like `(global-set-key (kbd "M-m f P") #'treemacs-projectile)`.

I've also pushed a fix for the collapse dirs issue now.

> I forgot to mention that the icons are still missing despite using the use-package configuration for treemacs.

All right, we will try one last thing before I go with the easy and ugly workaround of just using some random color if none can befound. Run `C-h f face-attribute`. You'll see a help buffer that says something like "face-attribute is a compiled Lisp function in 'faces.el'". Click on that faces.el button and you'll land in the code that defines the `face-attribute` function. Paste that code here - I want to know if we're running the same code. I'm on emacs 26, so maybe there's been some change in the meantime.

**Comment by kinleyd** [comment] 2017-10-03 15:00
I'm on emacs 25.3 on Arch Linux. 

Function face-attribute:

(defun face-attribute (face attribute &optional frame inherit)
  "Return the value of FACE's ATTRIBUTE on FRAME.
If the optional argument FRAME is given, report on face FACE in that frame.
If FRAME is t, report on the defaults for face FACE (for new frames).
If FRAME is omitted or nil, use the selected frame.

If INHERIT is nil, only attributes directly defined by FACE are considered,
  so the return value may be `unspecified', or a relative value.
If INHERIT is non-nil, FACE's definition of ATTRIBUTE is merged with the
  faces specified by its `:inherit' attribute; however the return value
  may still be `unspecified' or relative.
If INHERIT is a face or a list of faces, then the result is further merged
  with that face (or faces), until it becomes specified and absolute.

To ensure that the return value is always specified and absolute, use a
value of `default' for INHERIT; this will resolve any unspecified or
relative values by merging with the `default' face (which is always
completely specified)."
  (let ((value (internal-get-lisp-face-attribute face attribute frame)))
    (when (and inherit (face-attribute-relative-p attribute value))
      ;; VALUE is relative, so merge with inherited faces
      (let ((inh-from (face-attribute face :inherit frame)))
	(unless (or (null inh-from) (eq inh-from 'unspecified))
          (condition-case nil
              (setq value
                    (face-attribute-merged-with attribute value inh-from frame))
            ;; The `inherit' attribute may point to non existent faces.
            (error nil)))))
    (when (and inherit
	       (not (eq inherit t))
	       (face-attribute-relative-p attribute value))
      ;; We should merge with INHERIT as well
      (setq value (face-attribute-merged-with attribute value inherit frame)))
    value))

**Comment by Alexander-Miller** [comment] 2017-10-03 15:21
Nope, code's the same.
Oh well, I've pushed a workaround, when treemacs cannot find its colors as its loading it will now spit out some warnings and use #2d2d31 as a fallback color. It wont look right, especially on bright themes, but at least the icons should be around now.
Let me know if this works for you.

**Comment by kinleyd** [comment] 2017-10-03 15:30
Thanks @Alexander-Miller, appreciate your time and effort. Should I be waiting for the next build of treemacs for the changes?

**Comment by Alexander-Miller** [comment] 2017-10-03 15:33
Yes. I've also bumped the version. You know you have the update when youre running v1.11.4.

**Comment by kinleyd** [comment] 2017-10-03 16:34
Thanks, it's working now. Here's what it looks like:

![treemacs](https://user-images.githubusercontent.com/1420223/31136762-e52633cc-a88a-11e7-9c25-dc76d41045b9.jpg)

**Comment by Alexander-Miller** [comment] 2017-10-03 16:41
The background is borked, but it's better than nothing I guess. Just a few final checkups, and we're done.

 * Do you see the warnings in your log? Some that looks like `"[Treemacs] Warning: coudn't find default background color, falling back on #2d2d31."`
 * Does the icon background change when `load-theme` another theme?
 * How about when you run this code:
```
(setq treemacs--not-selected-icon-background X
      treemacs--selected-icon-background     Y)
(--each treemacs--icons
  (progn
    (treemacs--set-img-property
     (get-text-property 0 'img-selected it)
     :background treemacs--selected-icon-background)
    (treemacs--set-img-property
     (get-text-property 0 'img-unselected it)
     :background treemacs--not-selected-icon-background)))
```

Just replace X and Y with some color string, hex or something like "red". If this works you can use this code to manually fixup your icon colors.

**Comment by kinleyd** [comment] 2017-10-03 16:53
Yes, I see these:
[Treemacs] Warning: coudn’t find default background color, falling back on #2d2d31.
[Treemacs] Warning: couldn’t find hl-line-mode’s background color, falling back on #2d2d31.

Background changes with a change in theme, as seen here:
![treemacs](https://user-images.githubusercontent.com/1420223/31137419-10230f3a-a88d-11e7-9531-a22ed12d7506.jpg)

> setq treemacs--not-selected-icon-background X
      treemacs--selected-icon-background     Y)
(--each treemacs--icons
  (progn
    (treemacs--set-img-property
     (get-text-property 0 'img-selected it)
     :background treemacs--selected-icon-background)
    (treemacs--set-img-property
     (get-text-property 0 'img-unselected it)
     :background treemacs--not-selected-icon-background)))

gives me this:
![treemacs](https://user-images.githubusercontent.com/1420223/31137606-954e5692-a88d-11e7-87eb-4d178d3572cf.jpg)

**Comment by Alexander-Miller** [comment] 2017-10-03 17:05
Ah, good. You can use that code to get your gray8 and darkolivegreen set up as it should be. 

This issue is as resolved as its going to be, but lets keept it open until I add an FAQ section where I can explain those disppearing icons.

**Comment by kinleyd** [comment] 2017-10-03 17:06
Awesome! And thank you!

**Comment by seagle0128** [comment] 2017-10-03 17:18
Great! Then I can drop `neotree`, and use `treemacs` in the daily work.

**Comment by Alexander-Miller** [comment] 2017-10-03 17:21
You may also want to watch https://github.com/Alexander-Miller/treemacs/issues/53, my last comment specifically. Non-image icons may better fit with your minimalistic font. Though the final change wont come very soon - first I want to finish making treemacs frame-local, since that will vastly simplify the whole do or do not use image icons choice.

**Comment by kinleyd** [comment] 2017-10-03 17:28
Thanks, I will track that, and yes, I would prefer non-image icons. I shall wait patiently. :)

**Comment by sound2gd** [comment] 2017-10-05 09:19
sorry for late reply,  glad to see it solved.

**Comment by Alexander-Miller** [comment] 2017-10-05 12:35
Let's keep this open. I need a reminder to add a section about this to the readme.

**Comment by Alexander-Miller** [comment] 2017-11-18 16:14
* Added an FAQ entry about treemacs needing to look up your theme's background colors and how to set them.
 * Also added readme section on how to customize all icons that treemacs uses.
 * Also added option to force simple icons with ~treemacs-no-png-images~.

I believe that covers the remaining todos here.

**Closed by Alexander-Miller** 2017-11-18 16:14 UTC
